### ISSUE TITLE
https://streamaserver.org/ is down

### ISSUE THREAD

**Issue by aopom** [streamaserver/streama#1017]
Hello,
First thanks for this amazing project, I use it since approximately a year.
I wanted to check something in the documentation on the website and saw that it is down.
Has the website moved or something ?

**Comment by LukeSteward** [comment]
Hi @aopom,

The docs have moved to https://docs.streama-project.com/  and the demo version is available on https://streama.demo-version.net/ 

If this has solved your query please mark this as complete

**Comment by dularion** [comment]
Updated, thanks! I never understood where the old link was still coming from. :D
