### ISSUE TITLE
The android app is no more on the Play Store

### ISSUE THREAD

**Issue by aopom** [streamaserver/streama#1018]
Hello,
As issues are closed for the Streama Android app, I post the issue here.
I discovered the existence of the app and noticed that it is not on the Play Store as mentionned in the Readme.
@dularion, would you consider uploading it again ? Did you have any issues with the Play Store ?
Thanks

**Comment by arindammitra06** [comment]
APK is here incase if you wanted it without building it..

https://github.com/streamaserver/streama-app/releases/tag/0.3.0
