### ISSUE TITLE
Discord please 

### ISSUE THREAD

**Issue by H3rmit** [streamaserver/streama#1026]
### Issue description
i have a lot of questions but mostly my self and im sure a lot of others would love to see a discord server put up.

### Steps to Reproduce

1. TODO
2. TODO
3. TODO

### Expected Behaviour
Tell us what should happen

### Actual Behaviour
Tell us what happens instead

### Environment Information

- **Operating System**: TODO
- **Streama version**: TODO
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: TODO
- **Container Version (If Applicable):** TODO

**Comment by LukeSteward** [comment]
Hi @H3rmit,

We already have a discord community https://discord.gg/CJEHWX9

If this has resolved your issue please mark this as complete.

Many Thanks,

**Comment by H3rmit** [comment]
thanks!
