### ISSUE TITLE
 An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by peterpt** [streamaserver/streama#1041]
### Issue description
Just updated to latest streama version and run it , when i go look into the log file to see if there was any issue i got this :

root@mail:/var/log# cat streama_server.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (jar:file:/data/streama/streama-latest.jar!/BOOT-INF/lib/groovy-2.4.7.jar!/) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO streama.Application - Starting Application on mail with PID 16517 (/data/streama/streama-latest.jar started by root in /data/streama)
DEBUG streama.Application - Running with Spring Boot v1.4.4.RELEASE, Spring v4.3.6.RELEASE
INFO streama.Application - The following profiles are active: production

Configuring Spring Security Core ...
... finished configuring Spring Security Core

Configuring Spring Security LDAP ...
... finished configuring Spring Security LDAP

----------------------------------------------
Despite this error the app is running fine .

**Comment by dularion** [comment]
Please refer to https://issues.apache.org/jira/browse/GROOVY-8339
