### ISSUE TITLE
No option to un-highlight a movie on the dashboard

### ISSUE THREAD

**Issue by SquidLiquid224** [streamaserver/streama#1049]
### Issue description
There is no option to un-highlight a movie on the dashboard once it is highlighted.

### Steps to Reproduce

1. Upload local file as a movie
2. Highlight the movie on the dashboard

### Expected Behaviour
Highlighted movie would have an option to un-highlighted

### Actual Behaviour
Highlighted movie is stuck on the dashboard

### Environment Information

- Windows 10 64bit
- 1.10.3
- Streama for Student Films database 
https://github.com/SquidLiquid224/streama

**Comment by dularion** [comment]
you can actually delete them in the dedicated dashboard-highlights area of the Content-Manager Administration. 

![image](https://user-images.githubusercontent.com/936076/110169131-84e69f00-7df8-11eb-9bcb-0c23b09418ba.png)

**Comment by SquidLiquid224** [comment]
Thanks! I can't believe I didn't see that.
