### ISSUE TITLE
Genre are not selectable in manually created movies 

### ISSUE THREAD

**Issue by dularion** [streamaserver/streama#1054]
![image](https://user-images.githubusercontent.com/936076/110170845-1525e380-7dfb-11eb-86d0-175a70fa0f33.png)

**Comment by SquidLiquid224** [comment]
![image](https://user-images.githubusercontent.com/29264665/110171480-c449c700-7dc9-11eb-881c-08cce351d1dc.png)

**Comment by SquidLiquid224** [comment]
My coworker and I figure it out by commenting out <div ng-hide="addManually">
In 
grails-app/assets/javascripts/streama/templates/modal--movie.tpl.htm

**Comment by SquidLiquid224** [comment]
My coworker and I figured it out by 
commenting out:
div ng-hide="addManually"
in 
grails-app/assets/javascripts/streama/templates/modal--movie.tpl.htm

**Comment by elnicko** [comment]
Any chance this gets released officially?

**Comment by dularion** [comment]
sure, can you make a pr?

**Comment by elnicko** [comment]
Ehm... I'm not sure I understand your request for a PR... AFAICU this thread, the change has been pushed by you on 5. March 2021 to branch v1.11, so 2.5 yrs or so ago. Isn't it more appropriate to cherry-pick? Or even release v1.11?

https://github.com/streamaserver/streama/commit/35ee3543b517ac32f6c20c216d6dca76f5d3a298

**Comment by dularion** [comment]
ah! havent been active here forever, so didnt remember this at all :D

**Comment by dularion** [comment]
done :) 
https://github.com/streamaserver/streama/releases/tag/v1.10.5

**Comment by mrshanetuckeruk** [comment]
Thank you for releasing this. Just want to say that this is a fantastic project and application and I really appreciate the effort you all put into this.
