### ISSUE TITLE
Streama Player: Blank screen

### ISSUE THREAD

**Issue by mayank-pq2q4** [streamaserver/streama#1070]
### Issue description
I just downloaded and configured the streama server on my DigitalOcean server, and the problem I face is that it plays the audio but I only see a blank screen.

### Steps to Reproduce

1. Configured upload and a local folder, added the movieDB API key.
2. Created movie and chose the local video directory movie, which it successfully added
3. On playing the movie, it showed a black screen with only audio. I downloaded the movie into my local computer to see if the film itself was like that but it played flawlessly on my vlc, so not the video's problem. (Format: MKV)

### Expected Behaviour
It should play the movie completely.
### Actual Behaviour
It only streams a black screen and plays the sound

### Environment Information

- **Operating System**: Ubuntu 20.04 (LTS) x64
- **Streama version**: 1.10.3
- **Custom streama build, describe customizations or provide a link to fork (If Applicable)**: not a custom streama build
- **Container Version (If Applicable):**  not a container version (Installed via wget on the standard download documentation provided.)

**Comment by mayank-pq2q4** [comment]
Heres a [video](https://imgur.com/a/73047EN) of what it looks like(tested this on multiple services). For now, it only has one movie I downloaded on it.

**Comment by mayank-pq2q4** [comment]
Okay, so I tried it out on some smaller files(mkv) and to my surprise, it worked? still takes too long to stream but otherwise its.... fine? So I don't really know what is causing this then. Is is because my movie file is too large? Is it because I have 2 vCPUs
2GB / 60GB Disk?

**Comment by mayank-pq2q4** [comment]
Attempting reboot of my server. Maybe that should fix it

**Comment by mayank-pq2q4** [comment]
Just came across this
https://docs.streama-project.com/about/video-codecs/
mostly this might work. Will update.

**Comment by mayank-pq2q4** [comment]
IT WORKED!! seems like that was a codec issue indeed! glad I solved this one.

**Comment by GitEin11** [comment]
is there a way to use external video player?
