### ISSUE TITLE
How to disable downloading of videos? [QUESTION]

### ISSUE THREAD

**Issue by abneetwats24** [streamaserver/streama#1071]
I wanted to disable download ability for users, I.e. Admin post videos, and users can only watch them they should not download that video in anyhow.

**Comment by atmos-o** [comment]
Click "Admin" on the top right next to the user button, scroll down to "Let users download Videos" and untick that.
![image](https://user-images.githubusercontent.com/44858581/118243281-2db71780-b496-11eb-8b0b-ce3820a554c1.png)

**Comment by abneetwats24** [comment]
Thanks for your response.
