### ISSUE TITLE
Ability to pass configuration file on the command line

### ISSUE THREAD

**Issue by aopom** [streamaserver/streama#1073]
### Issue description

Is it possible to pass as an argument on the command line the path to the application.yml file ?
I know Streama looks in the working directory, but this is not practical, as I'm trying to package it for [NixOS](http://nixos.org), which has a strict vision of path management.

### Expected Behavior

Possibility to do something like this:
`java -jar /path/to/streama.1.10.3.jar --configurationFile /other/path/to/application.yml`
(The path to the h2 file is the YAML file)

### Environment Information

- **Operating System**: NixOS (Linux-based)
- **Streama version**: 1.10.3

**Comment by atmos-o** [comment]
If you use Docker-compose you can actually place that in a different location and specify it in the volume section of the compose file
![image](https://user-images.githubusercontent.com/44858581/118345216-f0509980-b52a-11eb-93ff-bbcf411c703a.png)

**Comment by aopom** [comment]
Yeah, thank you for this tip!
Actually, I'm trying to package the software on the host natively, not in a container.
I'm searching for a way to natively specify another path for the configuration file.

**Comment by aopom** [comment]
For reference for NixOS users,
I created a directory with the jar and yaml with this code:
```nix
  workingDir = pkgs.linkFarm "streama-pwd" [
    { name = "application.yml"; path = config; }
    { name = "streama.jar"; path = jarFile; }
  ];
```
my full configuration for Streama is [here](https://framagit.org/ppom/nixos/-/blob/3e8d4f680e1ced7a6419c14816894d1ded43ccf0/modules/musi/streama.nix)
