### ISSUE TITLE
Similar Movies Suggested by TheMovieDb.org

### ISSUE THREAD

**Issue by bombolini** [streamaserver/streama#1078]
Hello,
Thank you for your nice app. Just have one problem. 
I do not know why images do not appear under "similar movies suggested by themoviedb.org"
All other art covers are fine.

**Comment by coatmaker618** [comment]
Strange, they do for me.

**Comment by coatmaker618** [comment]
@bombolini I assume you closing this means you found a solution?  What was it?

**Comment by bombolini** [comment]
no, not yet. Since you said it works as expected at your end, I looked all my installation steps with suspicion.
I suppose there are some misconfigured directories, permissions/chown as well in my settings
