### ISSUE TITLE
down after a while

### ISSUE THREAD

**Issue by bombolini** [streamaserver/streama#1118]
### Issue description
I am running 1.10.4
After couple of hours, the url is unacessible.
Process is killed somehow.

### Steps to Reproduce

1. TODO
2. TODO
3. TODO

### Expected Behaviour
Tell us what should happen

### Actual Behaviour
Tell us what happens instead

### Environment Information

- **Operating System**: TODO
- **Streama version**: TODO
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: TODO
- **Container Version (If Applicable):** TODO

**Comment by osevenlan** [comment]
If you're running linux, try starting Streama via tmux instead of just a normal session - this will allow you to disconnect without killing off the app!

**Comment by bombolini** [comment]
thank you
