### ISSUE TITLE
[Not a issue!] | Please Read. (i have created a fan reddit community.)

### ISSUE THREAD

**Issue by justinweichTV** [streamaserver/streama#1125]
Hey, I love your program. I've been using it for a long time, I thought it was a shame there wasn't something like a community Discord server or a Reddit community.
so i created a fan community.
that people from the community and the developers can exchange ideas.

i can of course understand if this "post" is deleted, because this is an advertisement and this is not an issue report.

to the developers, if you contact me, i will give you admin rights on this reddit community. if you want, i will also transfer the ownership rights.

Reddit Community link:
https://www.reddit.com/r/streama

**Comment by LukeSteward** [comment]
Thank you for this while I am not the maintainer I would suggest speaking with some of the community on our discord
https://discord.gg/CJEHWX9

Please note this project is no longer actively developed.
