### ISSUE TITLE
[NOT A ISSUE]

### ISSUE THREAD

**Issue by FrosTechnology** [streamaserver/streama#1126]
Is there more information on how to do the database and build form source from Windows?

**Comment by FrosTechnology** [comment]
Also how to link my own domain?

**Comment by LukeSteward** [comment]
https://github.com/streamaserver/streama/wiki/Compiling-the-source-code

If you get stuck reach out on our discord for community support
https://discord.gg/CJEHWX9

Please note this project is no longer actively developed.
