### ISSUE TITLE
Make TheMovieDB optional

### ISSUE THREAD

**Issue by SajeOne** [streamaserver/streama#125]
Right now using a moviedb API key is required by streama. Unfortunately to obtain one you are forced to enter in sensitive information which I would rather not give out freely. Is there any chance of making the API key optional? And being able to manually enter the show/movie info yourself?

This looks like an excellent app and I would love to use it. Thank you for your time.

**Comment by dularion** [comment]
Ok wow, never thought about that! That requires a lot of changes as it's hooked into everything but I'll see what I can do!
