### ISSUE TITLE
Parsing genres from TMDB - Feature Request

### ISSUE THREAD

**Issue by imkimchi** [streamaserver/streama#264]
I wonder why It doesn't parse the genre information from TheMovieDB.
You can parse genre information easily using their APIs like below!

`/search/movie` API returns genre_id array and then you can get the corresponding name of the genre_id's using `/genre/movie/list`API.

Would you like to add this feature?

**Comment by dularion** [comment]
I've noticed this too. This is already happening on restart of the app, in the Bootstrap.groovy but I agree that it should happen when adding movies and shows

**Comment by dularion** [comment]
Oh wait, I am not sure I am following. I thought you were talking about something else. How do you mean, parse? As in, it should appear for search results?

**Comment by imkimchi** [comment]
After add a movie, It doesn't show up genre of its movie so users should add genre manually. I thought its supposed to be generated automatically by the service.

**Comment by dularion** [comment]
It is... I'll have to debug further

**Comment by imkimchi** [comment]
Did you fix this issue?

**Comment by dularion** [comment]
Sorry, not yet. but will get to it soon

**Comment by dularion** [comment]
added a feature now where you can manually adjust the genre, too.

**Comment by dularion** [comment]
I've addressed this bug for "Similar Movies". I cannot reproduce it anywhere else. please reopen if you find more occurences of genres missing.

**Comment by dularion** [comment]
Found out that it also happens for BulkCreated files. Resolved in v1.7.0-RC10
