### ISSUE TITLE
account login security

### ISSUE THREAD

**Issue by mazzucato** [streamaserver/streama#271]
control the account login, like if its logged others cant login at your account elsewhere...

**Comment by dularion** [comment]
I think thats interesting, however, I think some ppl use this "lack of security" as a feature, to share admin logins etc. How do you and others feel about that?

**Comment by mazzucato** [comment]
As it has the possibility of creation and management of several accounts I do not see interesting sharing of access even if it is for content management

**Comment by Niach** [comment]
i think to make it optional would be the best approach here.
technically it could be done with the ip adresses as stated in #212 so that people can use all their devices at once, but not multiple people with the same account

**Comment by dularion** [comment]
issue #212  just addresses logging of user activity, but I agree that this could be interesting. maybe in conjuction with subscriptions and plans? #231

**Comment by mazzucato** [comment]
really liked the #602 idea...
