### ISSUE TITLE
Add option to download video

### ISSUE THREAD

**Issue by jguerinet** [streamaserver/streama#283]
It would be nice to have a download button on the different video files. This would be a temporary solution to unsupported video formats: if the video file you are trying to read is in an unsupported format, you could at least download it to watch locally on your device.

**Comment by xlogik** [comment]
I believe downloading a video you don't own would most likely violate some copyright law. The safer option would be to implement the BitTorrent protocol with something like [WebTorrent](https://github.com/feross/webtorrent).  Check out Issue #262 and #265

**Comment by jguerinet** [comment]
Right, but since the videos that are initially available for viewing on your Streama were uploaded by yourself (i.e. the admin), don't you theoretically have the ownership rights on these videos? Of course we are talking about the ideal case here, but since you are the one who is making this content available (and you have access to the actual files since you're uploading them in some way) it would make sense that technically you would have secured all of the rights for these files. 
But I'll keep an eye out on #262, that issue is interesting on its own

**Comment by dularion** [comment]
So in the 1.6.0 release, I've added support for this. I made it optional though, so the site-admin can choose whether or not the download button shows up. In the future I intend to group some of the player options together, but for now it works like this: 

## In the admin panel 
![image](https://user-images.githubusercontent.com/936076/39488686-49289e58-4d83-11e8-85f2-ddf1063dac23.png)


## in the player
![image](https://user-images.githubusercontent.com/936076/39488714-5e23ea74-4d83-11e8-8bf3-80711f113d9b.png)

**Comment by jguerinet** [comment]
Beauty. Thanks for considering this and for all of your hard work in general. This is fantastic. 
Is this part of RC2, or will it be part of the official release? If the latter, do you have an idea of when that would be?

**Comment by dularion** [comment]
its up :) https://github.com/streamaserver/streama/releases/tag/v1.6.0-RC3
feel free to test it out and give me feedback if anything seems off

**Comment by jguerinet** [comment]
Awesome! I'll update tonight when I get home. 
I'll close the issue for now and re-open if anything is wrong. Thanks again!

**Comment by dularion** [comment]
thank you :) !

**Comment by jguerinet** [comment]
Hey @dularion, 

The feature is looking good. One (non-blocking) recommendation I would make is the naming of the downloaded file. Currently it just uses its DB ID as the name. What are your thoughts on maybe calling it either the movie/file name for movie/other videos, or `Show S01E01 - Title` for TV shows? There would need to be a check to make sure that illegal characters aren't included (One example that comes to mind is `:` would need to be replaced by something like `-`). 
Again, not a huge deal if you want to keep it the way it currently is. If you are interested in changing, I can either re-open this issue or create a new one. Whatever works best!

**Comment by dularion** [comment]
Ok so ive added functionality that the downloaded file gets the original file name stored in the DB. this is done as per https://www.w3schools.com/tags/att_a_download.asp. Hwoever, afaik this doesnt have full browser support. But let me know how it feels. you can test it out here https://github.com/streamaserver/streama/releases/tag/v1.6.0-RC4. Beware however that another change in the RC4 might break some stuff. Feel free to report any bugs you find on that front, I always appreciate when others help me test :)

**Comment by jguerinet** [comment]
I quickly tested it and it looks good! So far nothing has broken for me (keep in mind I have only tested local file links as this what I am currently using). The file names are working nicely for me (I'm on Chrome). 
I'll close this for now, and re-open if I have any problems with it. And I'll open another issue if I run into a bug on RC4. Thanks!

**Comment by dularion** [comment]
Thanks mate :)

**Comment by antibios** [comment]
One potential problem here is that when the video format is not supported (.mkv for example) it does not show the player to allow the user to download.  Would it be considered to move the download option to the movie info page or as a option instead of playing?
