### ISSUE TITLE
File manager not working

### ISSUE THREAD

**Issue by d000000h** [streamaserver/streama#302]
The file manager doesnt seem to be working at the moment at least for me

Running on Ubuntu

i dont use mysql to store data mostly default settings

here is gif to show the problem

![streama](https://cloud.githubusercontent.com/assets/10897164/23023085/271a3ef4-f454-11e6-9061-cdbda86f7814.gif)

**Comment by robsonolivesa** [comment]
i have the same problem. Im running in Unbuntu too.

**Comment by dularion** [comment]
will check it out

**Comment by CSCG** [comment]
This isn't fixed; still occurring on Ubuntu 16.04 as of 4/8/2017

**Comment by 2knarf** [comment]
Still have the problem both under Oracle 8 and OpenJDK 8

**Comment by dularion** [comment]
I can't reproduce this problem... The file manager works for me. Can you give me access to your installation so i can debug?

**Comment by LukeSteward** [comment]
Are you still having this issue in the latest version or can we close this issue?

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.
