### ISSUE TITLE
Subtitle SRT Character error

### ISSUE THREAD

**Issue by weslleycsil** [streamaserver/streama#337]
Hello,

Every time and I upload a .srt caption with special characters when viewing in the player I see strange characters.

I convert online from srt to vtt and the error has stopped, I believe the error is in the form of conversion.

thanks

**Comment by Flex101** [comment]
I wonder if this is linked to issue #284?

**Comment by mongomay69** [comment]
i don't believe so, #284 was more about the title of the video and not about manually uploaded .srt files. as a question for weslleycsil, what browser are you using?

**Comment by LukeSteward** [comment]
This issue is when subtitles are not saved as utf8 we have tested this on the discord with other users and have found that it supports all Unicode characters if you change the .srt file. This is the same problem as #840
