### ISSUE TITLE
Feature Request: 'To Watch' List

### ISSUE THREAD

**Issue by jguerinet** [streamaserver/streama#339]
Hi, 

I was thinking it might be useful to add a feature where a user could add videos they want to watch into their own personal list. I see it working very much like the "My List" feature on Netflix, but on a per episode basis rather than a show basis. For example, I have a list of episodes from different TV shows that I would like to watch, but currently the only way for me to keep track of these episodes is for me to keep a separate list on my phone, and then look it up whenever I open Streama. It would be nice to be able to add an episode to a To Watch list (or whatever you want to call it), and have that be a section in the dashboard. 

Thanks, 
Julien

**Comment by ManuGithubSteam** [comment]
Cool idea i secon this :-)

**Comment by dularion** [comment]
Cool idea indeed. Will add it to the roadmap
