### ISSUE TITLE
Xbox One - Semi Supported

### ISSUE THREAD

**Issue by CSCG** [streamaserver/streama#360]
Hey all,

Just documenting my progress. Using the Edge browser on X1, we can easily hoist Streama to the big screen with little adjustment. Log in works, UI works well. A little clunky compared to native but hey, it's a web emulator.

The issue thus far is the fact that .mkvs don't work; which is odd, as X1 claims to support. .AVIs actually don't work either, but normal .mp4s do. I'm experimenting currently with ffmpeg, just adjusting the container to see if this works. If that works in theory, then in actuality; all the needs to happen is a mass rename of .mkv to .mp4 and a remap of my files.

Long story longer - I'm trying to determine what exact set up of video format is required to have Streama working flawlessly on X1. Even the screen share live sync works; just the format issue.

-cs

**Comment by Jeronimo95** [comment]
So I think that the Edge browser will only support .mp4, since it's just a html5 browser. The video player app on the x1 will support the mkvs; but the browser will only support html5 formats. This probably won't be an issue when we implement video converting/transcoding in the future.
