### ISSUE TITLE
Synology nas

### ISSUE THREAD

**Issue by dancemaker711** [streamaserver/streama#383]
Is there a way to get it working on a synology nas , i have all my movies and series on there, its cool to have streama on there as well

**Comment by dularion** [comment]
oh .. I don't know a thing about Synology nas. Any way you can run it on a simple ubuntu / linux setup and hook in the nas as a mount or something?

**Comment by dancemaker711** [comment]
No thats not possiable, im working on a server hook for it the nas has an sort of appstore so im looking into it

**Comment by klincheR** [comment]
synology nas are running on linux so it should work somehow

**Comment by mickah** [comment]
If you have a Synology in this [page](https://www.synology.com/en-global/dsm/packages/Docker) you can install docker via the store and you should be able to run streama in a container.
If your nas is not in the list and if it run on ARM cpu it will be really painful (you may need to cross compile several dependencies ...)

**Comment by gavinwy** [comment]
@dancemaker711 Could you tell us which model of NAS you have?

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.
