### ISSUE TITLE
Needing to press f5 when logging in

### ISSUE THREAD

**Issue by vaguiners** [streamaserver/streama#400]
I'm setting up a streama site. At first everything worked OK, but after adding some series, something started to happen.

When the user logs in, nothing appears. You need to press f5 when logging in to show the series.

It seems to be something involving cookies, since F5 is only needed at the first log in. If the user log off without closing the page and logging in again, everything will appear normally.

**Comment by dularion** [comment]
Ok Thanks, I will look into it. Keep that demo access up as long as possible, I might not get to it soon

**Comment by dularion** [comment]
I cant seem to be able to recreate this. Can you give me access to your hosted version? Alternatively, check if the problem persists  here: https://github.com/dularion/streama/releases/tag/v1.2_beta

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.
