### ISSUE TITLE
[Help] Modal Media Detail Window

### ISSUE THREAD

**Issue by Apevia** [streamaserver/streama#408]
![modal-details](https://user-images.githubusercontent.com/28666042/28994580-e069d8b2-79d1-11e7-8d80-8b528d6cc060.png)

hey how do I make the modal-media details popup windows to your own new window no popup anymore?

**Comment by dularion** [comment]
How do you mean, its own new window? do you want a page separate from the dashboard where you can see a media page? a little bit like the detail-page of the admin area, only for all users?

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.
