### ISSUE TITLE
post-play when?

### ISSUE THREAD

**Issue by vaguiners** [streamaserver/streama#435]
cool feature
https://s.aolcdn.com/hss/storage/adam/20bd52eace38806c6f4c4b091c84f763/auto_play_lilyhammer.jpg
http://www.technologytell.com/gadgets/files/2012/08/Breaking-Bad.jpg

**Comment by Jeronimo95** [comment]
Definitely a cool feature. Not sure when we'll be able to do it, but will keep it in mind.
