### ISSUE TITLE
Cant add subtitles, it gives me file extension error and its srt.

### ISSUE THREAD

**Issue by ChiefVitor** [streamaserver/streama#439]

**Comment by Jeronimo95** [comment]
What version are you on?

**Comment by ChiefVitor** [comment]
last.

**Comment by Jeronimo95** [comment]
A version number would be more helpful but I'm going to assume v1.2.3_beta.

Could you attach one or two files that don't work?

**Comment by ChiefVitor** [comment]
[star.zip](https://github.com/dularion/streama/files/1315015/star.zip)

**Comment by Jeronimo95** [comment]
I can not reproduce.

* Download `https://github.com/dularion/streama/releases/download/v1.2.3_beta/streama-1.2.3_beta.war`;
* Run;
* Upload video file;
* Upload "`star.srt`";
* No errors are produced;
* Test playback with uploaded file, no errors are produced.

![image](https://user-images.githubusercontent.com/2177618/30778234-c56a7792-a113-11e7-9b8d-9b0558b14f2a.png)

**Comment by Jeronimo95** [comment]
Closing as no response.
