### ISSUE TITLE
Add support for RegEx matching in Settings Page w/Preview

### ISSUE THREAD

**Issue by Domush** [streamaserver/streama#447]
Please consider adding the ability to edit the RegEx matching (preferrably with the option to have multiple RegEx searches), where it performs a recursive file search in the Local Content directory for matches, so we know it works as intended.

Maybe, if that's too much effort, adding an "RegEx override" button next to the "Run Matcher" button, so we can ensure it matches what we want it to.

Honestly, it's silly to have us manually check each file box only to have the "Run Matcher" button tell us we wasted our time. Why not, upon a failed match, place a "Search TheMovieDb" search bar next to each failed match, so we can add them en mass instead of having to go through a click-fest?

Great work so far, though. It's impressive. Just lacking in usable features to add our current collections in any reasonable manner.

**Comment by Jeronimo95** [comment]
Good ideas. We'll keep them in mind for the future.

**Comment by dularion** [comment]
Thanks for your input @Domush  
We already have the option to add multiple regex searches, I am going to add a documentation for that shortly. 

About the feature "Search TheMovieDB" - I am not sure I am following: do you mean that the entire file hierarchy is crawled, recursively, for any matches?
In theory that shouldn't be a problem - in practice however tmdb has a limitation for searches per second, so you will run into limit-issues. 
But any ideas for a workaround would be appreciated :)

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.
