### ISSUE TITLE
Bulk adding subtitles

### ISSUE THREAD

**Issue by LittlePinkel** [streamaserver/streama#461]
Whenever I try to bulk add subtitles, after adding the video files, I receive the error that the files are already added. That means i have to manually add every single subtitle which takes a lot of time.

**Comment by dularion** [comment]
oh cool feature, they should maybe be imported together with the video actually

**Comment by varac** [comment]
What's the current best way of bulk-adding videos and subtitles, I can't find any ?

**Comment by stom66** [comment]
I don't believe there is one. Last time I tried bulk adding media and
choosing subtitles it recreated every episode as a new entry.

Currently I am selecting "close modal on select" and adding them
individually.

**Comment by dularion** [comment]
Good point, thanks for bumping this issue. Ill take a look at it now

**Comment by dularion** [comment]
Ok, Ive added a rough first draft of this feature in v1.7.0-RC9. Feel free to test it and give me feedback, that would be very helpful!

**Comment by dularion** [comment]
https://github.com/streamaserver/streama/releases/tag/v1.7.0-RC9

**Comment by varac** [comment]
Wow nice, works great on the first try !

**Comment by dularion** [comment]
ok let me know if this bugs out. Until then, ill close this issue as a success :)
