### ISSUE TITLE
cant reproduce external links on 1.3 beta

### ISSUE THREAD

**Issue by mazzucato** [streamaserver/streama#469]
external links not working inside streama 
they work fine when loading normaly on browser tab but when i try to watch on streama player it just give me that codec error and never reproduce the file

**Comment by Jeronimo95** [comment]
Are they direct like to HTML5 compatible files?

**Comment by mazzucato** [comment]
i think i cant send the link here but they are like:
 " http://my.domain/ondemand/bucket/files/temp/02-HIGH.mp4 "

**Comment by mazzucato** [comment]
thats my log file... created with setsid ./streama-1.3.0_beta.war > log.txt

https://pastebin.com/Ms9U9pc7

**Comment by mazzucato** [comment]
@Jeronimo95 digging around ive found that streama is getting the 400 error - bad request from the files server...

**Comment by Jeronimo95** [comment]
Are you sure that the external server is returning the file as an actual MP4, not as an HTML document? You said that "it just happens with a specific server" so it sounds as if that server is misconfigured.

**Comment by Duckbuster** [comment]
Can you wget the file from your server where streama is running?

**Comment by mazzucato** [comment]
yep
i can download the file or reproduce it on the browser 
just cant watch it on the streama player

**Comment by Jeronimo95** [comment]
@mazzucato is this still an issue with 1.4.2?

**Comment by ArchieGu** [comment]
@Jeronimo95 Hi, I got the same issue here. I used an dropbox share link. And ran into the codec error.
@mazzucato Do you have any solutions for this? Thanks.
