### ISSUE TITLE
Timer not working

### ISSUE THREAD

**Issue by guruiteu** [streamaserver/streama#515]
Hello, Thank you wery much for developing this project. I would like to inform you that timer isnt working when watching the movie it shows all the movie lenght. Also i would like to ask you please to fix the GENRE problem the Genr for movies and users dosn't work PLEASE FIX them. I'm starting to consider if this project will be continued to donate to developers.

And it would be nice IOS app. Thank you!

**Comment by dularion** [comment]
What's wrong with the movie genre exactly?
And what exactly is wrong with the timer? Can you send a screenshot and a description of the expected behavior?

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.
