### ISSUE TITLE
[Bounty] Plugin-based web player fork or external player launch compatibility

### ISSUE THREAD

**Issue by incorpusyehtee** [streamaserver/streama#555]
Hear me out or close this ticket. Thanks much in advance.

I am offering 300 USD or 500 USD bounties respectively:

 1. It is not a graceful solution at all to the lack of MKV/AC-3/DTS/etc support in Chrome/Firefox, whatsoever, but if anyone can fork this project with something like the DivX Web Player replacing the "streama player" I will pay you 300 USD. I would like to see the functional player demonstrated in a live instance which I can login to or via a remote desktop.

 2. Alternatively, for 500 USD, a fork of streama with support for external player mpv would be nice. Plugins like https://chrome.google.com/webstore/detail/play-with-mpv/hahklcmnfgffdlchjigehabfbiigleji?hl=en-US and https://addons.mozilla.org/en-US/firefox/addon/send-to-mpv-player/ work well enough for other sites, if someone can fork streama to add support for these plugins that would be nice. I would imagine this will require an HTTP GET-based (key param) method for `youtube-dl` or `mpv` to get to the video file since they cannot authenticate with the username/password.

It is fine that both of these systems will break resume support. 

I would like for the following to be delivered to me:

A clone of your build VM with JDK and groovy or whatever else is needed to maintain the fork with a short doc explaining the changes.

I can be reached at `my github user name`@`nym.hush.com` - thanks!

**Comment by dstutman** [comment]
Hi, I tried to reach out to you by email but was unable. Could you provide me with some more details of what you want for the $500 bounty? You can reach me at ```issues at githubforwarder.33mail.com```. Thanks.

**Comment by Jeronimo95** [comment]
Closing as no response.
