### ISSUE TITLE
make the default language configurable for all users

### ISSUE THREAD

**Issue by muhanadali100** [streamaserver/streama#584]
please can make the language default can change 

because some anonymous people want the strama in arabic language 

so the default language is english and can't change just if it login in

**Comment by dularion** [comment]
Ah ok, sure!

**Comment by muhanadali100** [comment]
please make it in 1.6.0 RC5

**Comment by Jeronimo95** [comment]
I've added a language select to the edit user modal. So in the next release you can change any users default language including the Anonymous user.
![image](https://user-images.githubusercontent.com/2177618/43363171-a3faafca-9341-11e8-8ebf-0e68abf534c3.png)
