### ISSUE TITLE
Related movies in "user view"

### ISSUE THREAD

**Issue by jtaverne** [streamaserver/streama#587]
# Hi, first of all, such a great work !!!! Really ;P
_I have some ideas so i'll open one issue by idea._

**First one ;P**

Is it possible to add related movies (which are available with movie attached on the server) when you open a detail movie screen ?

**Comment by Jeronimo95** [comment]
Glad you like Streama! And thanks for making one post per feature, that's really helpful.

Related movies on the detail screen should be possible.
