### ISSUE TITLE
Watchlist

### ISSUE THREAD

**Issue by jtaverne** [streamaserver/streama#590]
Is it possible to add some watchlist ?
You can select movies in order to view them letter or in irder to cataorize them as your own ?

**Comment by Jeronimo95** [comment]
Defiantly possible. I'm thinking like a button next to episodes, shows, and movies that adds to your list. Then the player can just run thought that playlist.

**Comment by sunjam** [comment]
I've seen this done as a heart shape "bookmark" tag that could be applied to films of interest.  Once watched, a "watched" tag would be applied.

**Comment by dularion** [comment]
I suggest a button in the dashboard cards like suggested above, but also in the media-info-dialog. Also, wee need a way to view our watchlist on the dashboard, so maybe a new section for that below "continue watching"? And a way to remove them from the watchlist. also, if a video is under "continue watching", should it then maybe automatically be removed from the watchlist? Or we should maybe add a "remove from watchlist" button for those items that are in a watchlist already... 

Also, watchlists should be different for different profiles, so the profiles need to be taken into account here. 


![image](https://user-images.githubusercontent.com/936076/68192798-3336c600-ffb2-11e9-8bf3-dbe3f5ccbb2c.png)
