### ISSUE TITLE
suggestion : add option to hide the continue watching

### ISSUE THREAD

**Issue by muhanadali100** [streamaserver/streama#610]
can you add option to hide the continue watching

**Comment by dularion** [comment]
Cool idea :)

**Comment by muhanadali100** [comment]
what happen to these suggestion ? you not add it

**Comment by dularion** [comment]
done in release RC7

**Comment by dularion** [comment]
@mcchan  i think there was a misunderstanding, the issue i believe was talking about the dashboard continue-watching section
