### ISSUE TITLE
Flexible filename matching

### ISSUE THREAD

**Issue by willmtemple** [streamaserver/streama#611]
## Problem
The regular expressions that Streama's currently using to match TV shows and movies are pretty restrictive (see streama/grails-app/services/streama/BulkCreateService.groovy). This is especially onerous for users that are migrating from Plex, which uses a different format for TV shows.

Furthermore, if neither of the regular expressions are matched, Streama silently fails to identify the file.

## Proposed Enhancement
It would be nice to support a handful of filename schemes, with optional components. At minimum, Streama should definitely support the name regex that Plex uses to make it easier/possible to migrate large libraries (I had to write a python script to rename files).

In the case that matching fails, the user should receive a more specific error informing them that the file name was not recognized, rather than a general error message.

It would be extra-nice if identifying a file didn't rely on its name at all. You could imagine that, if filename recognition fails, fall back to some kind of automatic content recognition or fingerprinting via. an API (similar to what Gracenote does for music, but open source). You could populate the database with data from well-structured libraries. I have no idea who would host such a thing, but there could be broader interest in the self-hosting community.

**Comment by dularion** [comment]
hi there! 
so firstly, you can actually adjust the regex however you like :) you can chain a bunch of OR-regex-matchers which then goes through each one to find a match. All you need to do is adjust the application.yml, see an example here: https://github.com/streamaserver/streama/releases/tag/v1.2.3_beta

secondly, I think your idea is good to improve the default-matcher. Would you be willing to play around with the matcher a bit to find the sweet spot and then send me your regex? then I can add it to the default regex we use currently, so for future installations admins wont have to input any fancy regex-override anymore.

**Comment by willmtemple** [comment]
Ah okay I see. I'm happy to spend a little time working on this.

As far as I know, the state of the art on this is github.com/Sonarrr/Sonarr, who have an [800-line parser class in C#](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/Parser.cs). It looks like it picks up just about everything, though I've never actually used their software.

They use like 70+ different regexes and a handful of model classes. I don't know how much of this behavior you want to replicate in Groovy or are willing to merge into Streama.

**Comment by dularion** [comment]
Oh ok, I tried to look at how KODI does it, and they use a single regex per type afaik. But maybe that has changed since the last time I checked. I guess we could implement something more complex, but before I do I think it would be interesting to see how far we can stretch this regex thing. What would be useful would be a list of names that currently dont match and that should match. If you could supply a first draft of such a list we can work on the regex together and see if we need to implement some code changes or if regex is enough

**Comment by dularion** [comment]
I'm now considering adding a list of regex for both shows and movies, so instead of having to build one gigantic regex, you can provide multiple alternative regex. Would that be a step in the right direction?
