### ISSUE TITLE
Edit Info Doesn't Save

### ISSUE THREAD

**Issue by Shrinks99** [streamaserver/streama#614]
### Issue description

When attempting to edit a movie's or TV show's description the webpage does nothing when the save button is pressed

### Steps to Reproduce

1. Go to a piece of content
2. Attempt to edit the content
3. Hit the save button

### Expected Behaviour

The application should save the content that I have edited

### Actual Behaviour

'Failed to load resource: the server responded with a status of 406'

### Environment Information

- **Operating System (Server)**: Ubuntu Server 17.10
- **Operating System (Client)**: Chrome, MacOS / Windows
- **Streama Version**: 1.5.0
- **NGINX Version**: 1.12.1

### Example Application / access to your live version

Live version access is possible upon request, addresses have been removed from the json and replaced with '192.168.1.11'

**Comment by dularion** [comment]
should be fixed in 1.6.0-RC5 thanks to @mcchan1991
