### ISSUE TITLE
I Can't create TV Show Maunally

### ISSUE THREAD

**Issue by EdgardoMartin** [streamaserver/streama#622]
When I create a TV Show manually. I can not place custom images (poster, cover, etc. in the episode to). Give an error message when uploading the image, close everything and try again. Any suggestions to create Programs manually? Thank you very much. Very good app

**Comment by Jeronimo95** [comment]
My suggestion would be to actually use the issue template and provide the error messages from the console and UI.

**Comment by EdgardoMartin** [comment]
This is the console error. 
 err Arguments​0: {…}​​error: 500​​message: "Internal server error"​​__proto__: Object { … }​1: 500​2: pa()​​arguments: null​​caller: null​​length: 1​​name: ""​​prototype: {…}​​​constructor: pa()​​​​arguments: null​​​​caller: null​​​​length: 1​​​​name: ""​​​​prototype: Object { … }​​​​__proto__: function ()​​​__proto__: Object { … }​​__proto__: function ()​3: {…}​​__XHR: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }​​file: File { name: "MusicaRomantica.jpg", lastModified: 1525305751000, size: 36822, … }​​headers: Object { "Content-Type": undefined, __setXHR_: __setXHR_() }​​method: "POST"​​sendObjectsAsJsonBlob: true​​transformRequest: Array [ upload() ]​​url: "file/upload.json"​​__proto__: Object { … }​callee: doUpload()​​arguments: null​​caller: null​​length: 1​​name: ""​​prototype: Object { … }​​__proto__: function ()​length: 4​Symbol(Symbol.iterator): undefined​__proto__: {…}​​__defineGetter__: function __defineGetter__()​​__defineSetter__: function __defineSetter__()​​__lookupGetter__: function __lookupGetter__()​​__lookupSetter__: function __lookupSetter__()​​constructor: function Object()​​hasOwnProperty: function hasOwnProperty()​​isPrototypeOf: function isPrototypeOf()​​propertyIsEnumerable: function propertyIsEnumerable()​​toLocaleString: function toLocaleString()​​toSource: function toSource()​​toString: function toString()​​valueOf: function valueOf() streama.unminified.js:4277:14
