### ISSUE TITLE
Can't add local image to Manual TV Show created

### ISSUE THREAD

**Issue by EdgardoMartin** [streamaserver/streama#623]
This is the console error.
err Arguments​0: {…}​​error: 500​​message: "Internal server error"​​__proto__: Object { … }​1: 500​2: pa()​​arguments: null​​caller: null​​length: 1​​name: ""​​prototype: {…}​​​constructor: pa()​​​​arguments: null​​​​caller: null​​​​length: 1​​​​name: ""​​​​prototype: Object { … }​​​​__proto__: function ()​​​__proto__: Object { … }​​__proto__: function ()​3: {…}​​__XHR: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }​​file: File { name: "MusicaRomantica.jpg", lastModified: 1525305751000, size: 36822, … }​​headers: Object { "Content-Type": undefined, setXHR: setXHR() }​​method: "POST"​​sendObjectsAsJsonBlob: true​​transformRequest: Array [ upload() ]​​url: "file/upload.json"​​__proto: Object { … }​callee: doUpload()​​arguments: null​​caller: null​​length: 1​​name: ""​​prototype: Object { … }​​__proto__: function ()​length: 4​Symbol(Symbol.iterator): undefined​__proto__: {…}​​__defineGetter__: function defineGetter()​​__defineSetter__: function defineSetter()​​__lookupGetter__: function lookupGetter()​​__lookupSetter__: function lookupSetter()​​constructor: function Object()​​hasOwnProperty: function hasOwnProperty()​​isPrototypeOf: function isPrototypeOf()​​propertyIsEnumerable: function propertyIsEnumerable()​​toLocaleString: function toLocaleString()​​toSource: function toSource()​​toString: function toString()​​valueOf: function valueOf() streama.unminified.js:4277:14

**Comment by Jeronimo95** [comment]
Somehow more useless than the last one.

1. Stop deleting the issue template.
2. Read the issue template. Read it before you type anything.
3. Provide the all the relevant info requested in the issue template. Including the stacktrace, which are the errors in the **server** console.
