### ISSUE TITLE
The user Activity don't sort correctly and cut off after 10

### ISSUE THREAD

**Issue by muhanadali100** [streamaserver/streama#625]
the user activity in 1.6.0 RC3 & RC4 not working
![desktop screenshot 2018 05 10 - 00 31 23 76](https://user-images.githubusercontent.com/31727156/39840887-a6060d42-53e9-11e8-9084-f1ea8c9c2dc2.png)

I login everyday but see the last login in 4-14-2018

**Comment by dularion** [comment]
fixed in [v1.6.0-RC5](https://github.com/streamaserver/streama/releases/tag/v1.6.0-RC5)
