### ISSUE TITLE
Streama wrongly appends :80 to domain during login redirect

### ISSUE THREAD

**Issue by seanthegeek** [streamaserver/streama#626]
### Issue description

Streama wrongly appends :80 to domain during login redirect

### Steps to Reproduce

1. Configure a [SSL reverse proxy](https://github.com/streamaserver/streama/wiki/Deploying-SSL-on-Niginx-on-Debian-or-Ubuntu) 
2. Login to the Strema web UI

### Expected Behavior

The browser should be taken the the Streama homepage

### Actual Behavior

After login, the browser is redirected to `https://streama.example.net:80/`, which is not a valid URL.

### Environment Information

- **Operating System**: Ubuntu Server 18.04
- **Streama version**: 1.6.0-RC1 (git master)
- **Custom Streama build, describe customization or provide link to fork (If Applicable)**: None
- **Container Version (If Applicable)**: None

**Comment by dularion** [comment]
Have you tried to map nginx to the 8080 port? It sounds to me like you used the application.yml to change the port to 80 but to do it properly you should use nginx or apache

**Comment by seanthegeek** [comment]
I didn't touch the default `application.yaml` that was created after I ran the application for the first time. I'm just using a nginx reverse proxy to port 8080.

**Comment by seanthegeek** [comment]
I added my exact configuration to the wiki here

https://github.com/streamaserver/streama/wiki/Deploying-SSL-on-Niginx-on-Debian-or-Ubuntu-(with-letsEncrypt-&-Certbot)

I don't think it is a nginx problem, because `:80` only gets appended after login, and not for any other web request. if I remove the `:80 from the URL myself at that point, its fine from then on, until the next login.

**Comment by wilsonjohns** [comment]
@seanthegeek Dude, have you figured this out? Same thing happened to me, I followed the instructions and now redirect to:80

**Comment by huangy10** [comment]
Here is the solution:

When writing nginx config file, add `proxy_set_header X-Forwarded-Port $server_port;` to proxy, like this:

```nginx
location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                #WebSocket Support
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;

                proxy_pass http://localhost:8080;
        }
```

**Comment by wilsonjohns** [comment]
@huangy10 Thank you very much! It worked for me :D

**Comment by DigitalFriends** [comment]
I'm still having issues with this, anyone that could explain with a little bit more details what needs to be done?

I'm also on Ubuntu 18.04.

**Comment by huangy10** [comment]
@DigitalFriends Have you tried my solution?

**Comment by DigitalFriends** [comment]
@huangy10 I'm sorry, i couldn't quite figure it out. 
Do you mind explaining it with a little bit more detail to it?

**Comment by Dorsug** [comment]
Got the same problem and the solution of @huangy10 worked for me too.
Should we close this issue?

**Comment by seanthegeek** [comment]
I just created a PR to put @huangy10's solution into the official documentation. I'm leaving the issue open until it is merged.

I also updated the old wiki page in case someone tries that.

Thanks @huangy10!

**Comment by f1reflyyyylmao** [comment]
Maybe close this issue since it's resolved?
