### ISSUE TITLE
JSON response with IMDB-ID and TMDB-ID

### ISSUE THREAD

**Issue by siteripper** [streamaserver/streama#632]
### Issue description
After "reduce data for files, subtitles & show data in video.json (as per #591)" the JSON does not give IMDB-ID or TMDB-ID anymore. This is very useful for implementation in Kodi-Plugins or other. (For example better scraping).
I agree with the reduction of data given away by Json but I think these infos would be useful.

### Expected Behaviour

Fetching IMDB/TMDB ID is possible

### Actual Behaviour

shows - imdb_idb:null

**Comment by dularion** [comment]
yes ok! ill add them back in
