### ISSUE TITLE
IP-Address for User Activity is wrong, always 0:0:0:0:0:0:0:1

### ISSUE THREAD

**Issue by dularion** [streamaserver/streama#633]
![image](https://user-images.githubusercontent.com/936076/40139998-fc533cca-5951-11e8-86a9-da77d4493769.png)

**Comment by muhanadali100** [comment]
![desktop screenshot 2018 05 17 - 13 55 27 40](https://user-images.githubusercontent.com/31727156/40173284-fc75f714-59d9-11e8-9b33-00aa69f1d0c1.png)

work with me

**Comment by Duckbuster** [comment]
I think it's if you run streama behind a proxy_pass (nginx)
Kinda like I already remarked in the pull:
https://github.com/streamaserver/streama/pull/601#issuecomment-387484958
