### ISSUE TITLE
make change picture

### ISSUE THREAD

**Issue by muhanadali100** [streamaserver/streama#635]
the picture is https don't cache and my network is slowly so the picture don't show

so can make the picture uploading from my PC , and the information from the network
![21](https://user-images.githubusercontent.com/31727156/40323309-aa63b29c-5d3d-11e8-99c8-ccd824ae110e.png)

**Comment by dularion** [comment]
Not sure what you are saying - caching should be enabled with or without https, see screenshot: 

![image](https://user-images.githubusercontent.com/936076/41512311-d6466eaa-7286-11e8-8b11-f1437dfeab99.png)


What exactly do you wish to improve?
