### ISSUE TITLE
Default bulk-add matcher regex is case-sensitive

### ISSUE THREAD

**Issue by stom66** [streamaserver/streama#636]
### Issue description

The default configuration for the bulk-add facilities matching utility appears to be case-sensitive. A series with files named in lowercase is not detected (eg `seriesname.s01e01.mp4`) whereas camelcase/caps works as expected (eg `SeriesName.S01E01.mp4`)

### Steps to Reproduce

1. Install Streama with default config
2. Use Bulk-Add feature to import a series with lowercase file names
3. Matcher will fail to find results
4. Rename files to camelcase format and it will work

### Expected Behaviour

Ideally filenames should not be case sensitive, and anything preceeding the `s00e00` string should be treated as the series name.

### Actual Behaviour

Files with all lowercase names are not matched correctly.

### Environment Information

- **Operating System**: CentOS7
- **Streama version**: v1.6.0-RC5
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: N/a
- **Container Version (If Applicable):** N/a

### Example Application / access to your live version

Available on request, please contact me via Discord.

**Comment by dularion** [comment]
Yes, you are correct. It should be case-insensitive. I'll add it to the regex execution
