### ISSUE TITLE
 DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND

### ISSUE THREAD

**Issue by aitrone** [streamaserver/streama#645]
Can not play video in browser Safari version 11.1.1 (13605.2.8)
V 1.6.0 RC6

 └─18392 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -jar /data/streama/streama.war

Jul 04 09:42:19 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:43:11 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:43:25 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:43:26 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:43:26 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:44:58 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:45:13 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:45:13 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:45:37 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
Jul 04 09:45:37 films Streama[18377]: DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND

**Comment by Jeronimo95** [comment]
This error means it can't read the file.

- Does the video file exist?
- Does Streama have permission to read the file?

**Comment by aitrone** [comment]
In chrome and firefox, everything works fine.
It seems to me with the right order once in other browsers everything works?

**Comment by Jeronimo95** [comment]
I can't reproduce with Mac OS X 10.12 16A323 and Safari 10.0 (12602.1.50.0.10)

**Comment by Jeronimo95** [comment]
Closed. Can't reproduce / no response.
