### ISSUE TITLE
No web interface

### ISSUE THREAD

**Issue by HappyGuy22** [streamaserver/streama#648]
Task List:
- [X] Issue description provided
- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Screenshots (if UI related) provided
- [X] Full description of the issue provided

### Issue description
I have installed streams as instructed [here](https://streamaserver.org/#easy-setup) But when I run the .war file it starts and when I try to connect to it, the page never loads. I have no tger services installed on the system. It's a fresh install of Raspbian Stretch.

### Steps to Reproduce

1. Download and install `openjdk-8-jdk`
2. Download latest streama release via `wget` command.
3. Make it executable.
4. download the sample_application.yml as application.yml and place it in the same directory as the war file. 
5. Run it by `/.streama.war`

### Expected Behaviour

After running the .war file, web interface should be available.

### Actual Behaviour

No web interface after running the .war file. But when I scanned the Pi with a network scanner, there's a service running on port 8080 but when I try to connect, the page never loads.

![screenshot_juicessh_20180719-134915](https://user-images.githubusercontent.com/29010784/42986696-33f4ebde-8c14-11e8-991f-de9757d8beb5.png)

### Environment Information

- **Operating System**: Raspbian Stretch Lite
- **Streama version**: 1.6.0 RC7
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: N/A
- **Container Version (If Applicable):** N/A

### Example Application / access to your live version

Not available

**Comment by HappyGuy22** [comment]
Also why does it require nearly **25 minutes** just to start the server?

**Comment by Jeronimo95** [comment]
A raspberry pi is generally too low power to run Streama.
I've seen similar issues with it talking an very long time to start on other low power machines.

We generally recommend a modern CPU and 2gb ram.

**Comment by HappyGuy22** [comment]
@Jeronimo95 Is there any plans to support Raspberry pis in future? Because plex has changed its privacy policy, I wanted to switch to streama but ... :(

**Comment by Jeronimo95** [comment]
It's my understanding that grails (the framework Streama is built on) is too heavy for low end systems. If anyone has insight into this it would be appreciated.

**Comment by Shrinks99** [comment]
System requirements should probably be posted in readme.md

**Comment by Jeronimo95** [comment]
Yeah I'm working on some new docs. System requirements will be more prominent.
