### ISSUE TITLE
Framedrop in Video, freezes player

### ISSUE THREAD

**Issue by ManuGithubSteam** [streamaserver/streama#657]
### Issue description

Some Video files have framedrops or the timecodes who are saying where the next frame is are not right and stream does not play them as it does not know where the next frame should i guess. However, mplayer and vlc do play the video fine. Cant explain more correct as my knowledge in video is limited.

Vlc does display visual artifacts when playing the file and getting to a position, where it should/could hang.

### Steps to Reproduce

1. Download my ripped copy of my DVD The Blacklist Season one. (https://ufile.io/e0im5)
2. Play with streama, see the video just stopping at certain points while playing. This can be overcome sometimes by scrolling forward in the video. 
3. play with mplayer or vlc and see the video continue like it should be

### Expected Behaviour

Steama uses the code vom VLC to overcome badly formated mp4 files and does not stop the video playback.

### Actual Behaviour

Streama freezes completly the video playback.

### Environment Information

- **Operating System**: Linux
- **Streama version**: Last stable one

### Example Application / access to your live version

not available

**Comment by Jeronimo95** [comment]
I highly doubt that this is an issue with Streama. It's more likely to be an issue with the video or the browser.



> "Vlc does display visual artifacts when playing the file and getting to a position, where it should/could hang." 

This leads me to believe that the issue is with the video and that VLC is just better at recovering.

If you can prove the issue is actually with Streama's implementation please re-open.
