### ISSUE TITLE
LG tv support/smart tv support

### ISSUE THREAD

**Issue by DrEthan77** [streamaserver/streama#671]
Hey I was thinking that smart tv support would be nice

**Comment by RUSshy** [comment]
duplicate of what issue ?

there is still no Android TV support

**Comment by HannahRy** [comment]
#74 is the smart TV issue

**Comment by DrEthan77** [comment]
wow thats a super old issue

**Comment by scsrat** [comment]
What is the chance of getting the ipk package for tv lg?
