### ISSUE TITLE
add proxy support

### ISSUE THREAD

**Issue by moeinrahimi** [streamaserver/streama#672]
hi can we have an option to define proxy in settings page by proxy i mean something like tor , movieDB is censored in my country and since streama is heavily depend on movieDB i can't use features like bulk create

**Comment by HannahRy** [comment]
**Note: I haven't tested this.**

You should be able to use a proxy by using a command like the folowing:

```
java -Dhttp.proxyHost=myProxy -Dhttp.proxyPort=myPort -Dhttps.proxyHost=myProxy -Dhttps.proxyPort=myPort -Dhttp.proxyUser=myUser -Dhttp.proxyPassword=myPass -jar streama.war 
```

(Obviously change the values to your own)

I don't think this will work with tor, you'll probably need to use some other program to route specific applications / outgoing addresses to tor. Integrating tor into Streama directly is out-of-scope for the project.
