### ISSUE TITLE
Feature request: pre conversion for streaming

### ISSUE THREAD

**Issue by lucaszanella** [streamaserver/streama#675]
Feature request: pre conversion for streaming

I'd like to stream some movies to some friends but they'll almost never be able to watch 1080p remotely, or even 720p sometimes. I think pre conversion is better for automated streaming on slow CPUs and it doesn't need to be heavily integrated into nodejs, it could just use ffmpeg or something alike to generate, for example: 1080p original, 720p good, 720p slow bitrate, 480p. I don't mind needing more 1TB of space to store these files, and if I add one movie per day, I think even if these conversions take one entire day, it'd be worth.

**Comment by HannahRy** [comment]
This will probably be a part of #440
