### ISSUE TITLE
Raspbian with docker support

### ISSUE THREAD

**Issue by lucaszanella** [streamaserver/streama#676]
```
FROM resin/rpi-raspbian:jessie

ENV DOWNLOAD_LINK=https://github.com/dularion/streama/releases/download/v1.4.2/streama-1.4.2.war

RUN apt-get update && apt-get install -y openjdk-8-jdk wget

VOLUME /data

EXPOSE 8080

ENV ACTIVE_PROFILE=docker

WORKDIR /app

RUN wget $DOWNLOAD_LINK -O streama.war

ENTRYPOINT /bin/sh -c "java -Dgrails.env=$ACTIVE_PROFILE -jar streama.war"

```

This is my dockerfile. When I do `docker run streama` everything hangs forever. Did anybody try to use it in raspberry and if yes, did anybody use docker? Could somebody try this dockerization I made?

**Comment by HannahRy** [comment]
It says very clearly in the docs that rpi's are too slow to run Streama and are not supported.
