### ISSUE TITLE
Feature: User Multi-Profile System (like netflix)

### ISSUE THREAD

**Issue by dularion** [streamaserver/streama#678]
After login, if multiple profiles exist, allow the user to switch:  
![image](https://user-images.githubusercontent.com/936076/46798781-37fb5d00-cd53-11e8-9847-6effa271201e.png)

Once logged in, add a profile-Switcher in the UI:  
![image](https://user-images.githubusercontent.com/936076/46798870-7002a000-cd53-11e8-899d-898d1574506e.png)

Allow to edit & add profiles: 
![image](https://user-images.githubusercontent.com/936076/46798943-ad672d80-cd53-11e8-94c7-d02867eb8337.png)

**Comment by mazzucato** [comment]
yay 

https://github.com/streamaserver/streama/issues/341 <3

**Comment by liberodark** [comment]
Great idea :D

**Comment by dularion** [comment]
This will be included as of release v1.6.0-RC10!
