### ISSUE TITLE
Its posible to compile app the app for webos?

### ISSUE THREAD

**Issue by DevUrbi** [streamaserver/streama#679]
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
Thanks for reporting an issue for Streama, please review the instructions below before submitting the 
issue. 

*****YOUR ISSUE WILL BE CLOSED IF IT DOES NOT USE THIS TEMPLATE OR IT IS INCOMPLETE!*****

Feature requests can be done without this template.  
If you have multiple things to report please create one issue per item.  
Please use english when reporting issues.  

If you are unsure about something and the issue is more of a question a better 
place to ask questions is on [gitter](https://gitter.im/dularion/streama).
DO NOT use the issue tracker to ask questions.

Please fill out the sections below the header and review the task list below.  
Task List:
- [ ] Issue description provided
- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Screenshots (if UI related) provided
- [ ] Full description of the issue provided

**PLEASE REMOVE THIS HEADER SECTION BEFORE SUBMISSION**
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------

### Steps to Reproduce

1. TODO
2. TODO
3. TODO

### Expected Behaviour

Tell us what should happen

### Actual Behaviour

Tell us what happens instead

### Environment Information

- **Operating System**: TODO
- **Streama version**: TODO
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: TODO
- **Container Version (If Applicable):** TODO

### Example Application / access to your live version

If available

**Comment by nbendall34** [comment]
Did you find a way to do this because I am trying to do the same...

**Comment by Saentist** [comment]
> Did you find a way to do this because I am trying to do the same...

It's need to have webframe app to use it on WEBOS.

**Comment by nbendall34** [comment]
thank you so much I spent all night trying to figure this out

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Saentist** [comment]
http://webostv.developer.lge.com/develop/app-developer-guide/hosted-web-app/
https://forums.webosnation.com/webos-development/216832-webview-load-html-string.html

**Comment by nbendall34** [comment]
Have you managed to do this?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Saentist** [comment]
Me no, but some one with expirience can do it.
Github is big comunity connect with some webos developer.

**Comment by nbendall34** [comment]
I will try

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
