### ISSUE TITLE
Allow more sections to be hidden on dashboard

### ISSUE THREAD

**Issue by bandicootdancing** [streamaserver/streama#687]
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
Thanks for reporting an issue for Streama, please review the instructions below before submitting the 
issue. 

*****YOUR ISSUE WILL BE CLOSED IF IT DOES NOT USE THIS TEMPLATE OR IT IS INCOMPLETE!*****

Feature requests can be done without this template.  
If you have multiple things to report please create one issue per item.  
Please use english when reporting issues.  

If you are unsure about something and the issue is more of a question a better 
place to ask questions is on [gitter](https://gitter.im/dularion/streama).
DO NOT use the issue tracker to ask questions.

Please fill out the sections below the header and review the task list below.  
Task List:
- [X] Issue description provided
- [X ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Screenshots (if UI related) provided
- [X] Full description of the issue provided

**PLEASE REMOVE THIS HEADER SECTION BEFORE SUBMISSION**
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------

### Issue description
I have a use case where I'd like to be able to hide the "discover movies" and "discover shows" sections. 

### Steps to Reproduce

1. Open up streama dashboard 

### Expected Behaviour
Ability to hide movies and shows. I have no movies or shows added so there are empty sections filling up page space. Custom videos are at the bottom.

### Actual Behaviour

Empty movie and shows category comes up before my custom media.

### Environment Information

- **Operating System**: Latest Streama war

**Comment by HannahRy** [comment]
Hiding the other sections has been added to master, will be in the next release.

Section names:
```
recommends
discover-shows
discover-movies
discover-generic
```

**Comment by githubber34** [comment]
Looks like this is not working properly.
Streama 1.8.0 on Firefox latest (71) on Mac.
Several attempts to hide one or more section(s) following the given syntax (with several attempts), they still appear (even after logging out / back in)
