### ISSUE TITLE
Bulk Create from file not work

### ISSUE THREAD

**Issue by liberodark** [streamaserver/streama#697]
Hi,

Have install and use Streama 1.6.0-RC9.
And try to add movies from folder : 

Exemple : How.It.Ends.2018.FRENCH.720p.WEBRip.x264.mp4
But no found but is on TheMovieDB.

Possibly regex ? https://regexr.com/

Cordialy

**Comment by HannahRy** [comment]
You can modify the Regex if its not right for your files.

https://streamaserver.org/config/application.yml/

**Comment by liberodark** [comment]
ok but what you not help me for that ?
And for what you no check this to find the problem ?
Have any problem with my issue ? is just a question a found a problem send you for try to find a solution
