### ISSUE TITLE
Help for Bulk-Create from file

### ISSUE THREAD

**Issue by liberodark** [streamaserver/streama#700]
Hi,

Is in reference of  https://github.com/streamaserver/streama/issues/697 !
Have add api (v3 auth) but is not find any movies for what ?
You have idea have make not good parameter ?

In Movies section : 

<a href="https://i.imgur.com/3hqips1.png">
  <img src="https://imgur.com/3hqips1l.png" />
</a>

Not found movies but series yes in english / All movies are on TheMovieDB have check and is a same name.

PS : Please not close is just for find solution !

Best Regards

**Comment by HannahRy** [comment]
Like I said before **you** can modify the regex for your media. We're not going to do it for you.

Please don't repeatedly open issues.

**Comment by liberodark** [comment]
ok no help for this :+1:  good
