### ISSUE TITLE
Download Button no longer showing up

### ISSUE THREAD

**Issue by jguerinet** [streamaserver/streama#706]
### Issue description
The Download button does not show up, even when enabled. This is 'fairly' new, I remember it working on RC6 I believe. 

### Steps to Reproduce

1. In your settings, make sure "Let users download videos" is checked
2. Open any video file

### Expected Behaviour

A button to download the raw file should be present on the player bar. 

### Actual Behaviour

The download button is no longer present. 

### Environment Information

- **Operating System**: Windows
- **Streama version**: 1.6.0-RC10

**Comment by wanderfyx** [comment]
Are your movies playing normally?

**Comment by jguerinet** [comment]
@wanderfyx Yes, no problems whatsoever with the playback (so far).

**Comment by jguerinet** [comment]
This is due to the new "Trusted User" setting that was introduced in #673. I had to go in and set all of my users to the trusted user role. 
One note: I think it makes sense that as an admin you are automatically a trusted user. 
There is another bug however that shows up when you delete a role: it deletes all of the roles. It was mentioned in the linked PR.
