### ISSUE TITLE
Movies not getting stored in the "continue-watching" section of the dashboard.

### ISSUE THREAD

**Issue by Norwelian** [streamaserver/streama#708]
### Issue description
I just noticed while watching a movie that if you close it (with the back button of the player), it doesn't get stored in the "continue-watching" section of the dashboard, as it should be.
Interestingly enough, it seems to work nicely with episodes from series, but not for movies.
I don't know when this started happening, but I remember it worked well a few months ago (sorry, just noticed it :( ).

### Steps to Reproduce

1. Clone streama
2. Configure it (application.yml)
3. Add a couple movies and episodes at random, just to test
4. Open an episode. Close it with the back button of the player. It gets stored in the continue-watching section on the dashboard for you to resume its play from where you left it.
5. Step 4 with a movie. Notice how it doesn't store any record of it in the continue-watching section of the dashboard.

### Expected Behaviour

When closed, a movie should store its playtime in the continue-watching section of the dashboard, as the episodes correctly do.

### Actual Behaviour

In the console, this gets printed:
```
ERROR grails.app.controllers.streama.ViewingStatusController - No such property: show for class: streama.Movie
```
I don't know how a project like this is structured (I understand the code, but I don't work with JS usually, so I don't know how the code is connected), so I'm currently unable to look further into this.
I've taken a look at the `grails-app\controllers\streama\ViewingStatusController.groovy` file, where I guessed the code of the controller is, but that's basically it.

### Environment Information

- **Operating System**: Win 7 x64
- **Streama version**: Last one (https://github.com/streamaserver/streama/commit/0a76d1b5f81197ad7522daa2c8874f4e0e2b8186 atm)

**Comment by Norwelian** [comment]
I've digged into this a little bit, and it seems to be an error caused by not handling a [ViewingStatus](https://github.com/streamaserver/streama/blob/master/grails-app/domain/streama/ViewingStatus.groovy) that doesn't have a `TvShow` set.
It cascades the following way:
[ViewingStatusController](https://github.com/streamaserver/streama/blob/0a76d1b5f81197ad7522daa2c8874f4e0e2b8186/grails-app/controllers/streama/ViewingStatusController.groovy#L29) tries creating a new [ViewingStatusService](https://github.com/streamaserver/streama/blob/0a76d1b5f81197ad7522daa2c8874f4e0e2b8186/grails-app/services/streama/ViewingStatusService.groovy#L30), which, in turn, tries creating a new [ViewingStatus](https://github.com/streamaserver/streama/blob/master/grails-app/domain/streama/ViewingStatus.groovy). 
[Movie](https://github.com/streamaserver/streama/blob/master/grails-app/domain/streama/Movie.groovy) does not have a `show` property, like [Episode](https://github.com/streamaserver/streama/blob/0a76d1b5f81197ad7522daa2c8874f4e0e2b8186/grails-app/domain/streama/Episode.groovy#L16) does, so it fails in [this line](https://github.com/streamaserver/streama/blob/0a76d1b5f81197ad7522daa2c8874f4e0e2b8186/grails-app/services/streama/ViewingStatusService.groovy#L30), trying to access the `show` property of a Movie.
A solution (I think) would be handling the type of the video being saved (movie or episode) and, in the case of a Movie, doing something (that I don't know) to create the ViewingStatus without accessing the `show` property.
Sorry for the messty explanation, hope the links clarify it a little!

**Comment by HannahRy** [comment]
I've just made a PR that will fix this. Rather than adding a TvShow to Movie I'm checking if the property exists and setting a variable based on that.

I just want @dularion to have a look at it first, it's pretty simple but there might be a better option.

**Comment by Norwelian** [comment]
Yeah, that's why I called it a "temporary" solution and didn't make it into a PR, 'cause I'm unable to do a better job at the moment in JS, but this does the trick neatly!
Thanks for the PR!
