### ISSUE TITLE
Playback should reset near the end of a video / next episode should show up on the dashboard

### ISSUE THREAD

**Issue by EchoDev** [streamaserver/streama#713]
If a video is in the last 5-10 second (maybe 20 seconds, a percentage or the outro that is set per show in the settings?) it should reset playback to the start of the video.

If you have watched an episode of a show and you return later to it to rewatch it, the video seems to just jump to the end since that is what was registered as last watched, it would be nice if a reset could be implemented at a predefined mark.

If I rewatch a show it just jumps from credits to credits now heh

**Comment by f1reflyyyylmao** [comment]
I think it'd be better to check for this when we add a video to the player: 
The player loads a video -> Checks if it's ~120s from the end (discussable, we should also check if it got a timestamp for the credits that we can use) -> If the time is over the threshold reset replay
This way the user can see what he already watched.

**Comment by dularion** [comment]
I added this feature n ow in the backend, when listing the continue-watching list. 
I also went for 95%, since it felt like it worked nicely for both tvshows and videos. 
Maybe down the road i'll make it configurable if anyone wants a different value
