### ISSUE TITLE
API keys are marked as invalid, tried two different keys

### ISSUE THREAD

**Issue by SoliElvis** [streamaserver/streama#714]
### Issue description
When configuring admin for the first time and copy pasting the api key obtained by creating new account and requesting api i can't save settings as the validate function returns invalid

### Steps to Reproduce

Fresh install and first time settings setup

### Expected Behaviour

correct api
### Actual Behaviour

invalid

### Environment Information

- **Operating System**: raspdebian
- **Streama version**: latest (1.6.0)

**Comment by EchoDev** [comment]
How long is your api key and where did you get your api key from?

The api key should be 32 characters long.

**Comment by EchoDev** [comment]
You shouldn't post your api key publicly. 

The key looks correct tho, it has the proper length and should work. Make sure you paste it without spaces at the beginning and end.

**Comment by SoliElvis** [comment]
It works now after reboot, same key, I don't know what caused the issue. There was some lag when pressing the validate key, seems like the app deadlocks in some invalid state through the web api. I'm closing it but I think there's a small bug somewhere or else the moviedb thing was down or something
