### ISSUE TITLE
add video converting

### ISSUE THREAD

**Issue by gman1918** [streamaserver/streama#716]
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------

### Issue description

can you on the fly video encoding
### Steps to Reproduce

1. TODO
2. TODO
3. TODO

### Expected Behaviour

Tell us what should happen

### Actual Behaviour

Tell us what happens instead

### Environment Information

- **Operating System**: TODO
- **Streama version**: TODO
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: TODO
- **Container Version (If Applicable):** TODO

**Comment by HannahRy** [comment]
Duplicate of 440
