### ISSUE TITLE
Streama doesn't remember where you left a series

### ISSUE THREAD

**Issue by f1reflyyyylmao** [streamaserver/streama#721]
### Issue description
When i watch a series where the order of episodes isn't really *that* important and i jump back to a previous one, streama always opens the episode with the highest episode number instead of the last one that i watched after returning to the dash and clicking play again. If i where to watch episode 130, jump back and watch episode 55, return to the dash and click the play button for that series in the "continue watching" section, it returns me to episode 130 instead of 55 where i left. 

### Steps to Reproduce

1. Add a series
2. Watch an episode with a high number
3. Watch an episode with a lower number
4. Press play in "continue watching"

### Expected Behaviour

It opens the last played episode

### Actual Behaviour

It opens the episode with the highest number

### Environment Information

- **Operating System**: Arch x64 both client and server
- **Streama version**: v1.6.0-FINAL
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: Has my current improvements for the german translation as described in #719 
- **Container Version (If Applicable):** None

**Comment by f1reflyyyylmao** [comment]
Now, i started looking into this myself, but I got stuck where the api-service sents a get request to `dash/listContinueWatching.json` as i could't find the backend that assembles the answer to the request. I assume that's where the issue is, as the episode number is already in the href field of the anchor tag in the "continue playing" section and there are no further requests after the "listContinueWathing.json" where that number could load from as far as i can tell

**Comment by f1reflyyyylmao** [comment]
Never mind, i just found the part that causes my issue. As soon as you accept my previous pr i'll open a new one fixing this.

**Comment by dularion** [comment]
Ok so I looked at the code more closely and I think what we need is a new functionality, that takes the newest ViewingStatus entry for a tvShow, not by episode-number, but by `lastUpdated` of the actual viewingStatus object. That way, we get the most recent activity of a user on a TV-Show

**Comment by dularion** [comment]
thanks for your contribution, merged it :)
