### ISSUE TITLE
Upgrading an "Admin"/"Content Manager" to a "Trusted User" removes all roles

### ISSUE THREAD

**Issue by stom66** [streamaserver/streama#729]
### Issue description
Upgrading an "Admin"/"Content Manager" to a "Trusted User" removes all roles

### Steps to Reproduce

1. Have both "Admin" and "Content Manager" roles.
2. Note: at this point the "Download Video" option does not appear in the player
3. Give self the additional role "Trusted User"
4. Log out and back in
5. Have no roles

### Expected Behaviour
I should keep the roles that are ticked and, ideally, not be un-"Admin"'d if I'm the only "Admin"

### Actual Behaviour

All roles are removed, potentially rendering a user unable to regain admin rights is they are using the standard method of data storage instead of a MySQL database.

### Environment Information

- **Operating System**: CentOS 7.5
- **Streama version**: 1.6.0-FINAL
- **Custom streama build: N/a
- **Container Version:** N/a

**Comment by dularion** [comment]
thanks to @mcchan hopefully fixed in next release
