### ISSUE TITLE
User Registration System. ( I read the previous reply but hear me out)

### ISSUE THREAD

**Issue by rajohn007** [streamaserver/streama#731]
I understand the logic behind not having a user registration system but The Admin cannot be always online to create user for particular user. Beside there's a Anonymous Access system which allow anyone to see content. Means the logic behind not having a registration feature is obsolete. So I am expecting Admin to have a registration system which can be turned off whenever Admin wants. If the honorable developer think this is a good idea please include this in next update.

**Comment by CardealRusso** [comment]
no 
close pls
if plan to iimplement make this very optional at adm panel
but i'm pretty sure we have more important things to work on at this moment

**Comment by dularion** [comment]
I have considered user registration, too, and yes, if we implement this it will be totally configurable in the admin-panel, so no worries.

**Comment by dularion** [comment]
Btw, is your request covered by https://github.com/streamaserver/streama/issues/602? in that case, maybe we can close this issue as a duplicate

**Comment by rajohn007** [comment]
Thank you for considering!
