### ISSUE TITLE
Suitable dedicated server

### ISSUE THREAD

**Issue by ProTechEx** [streamaserver/streama#735]
Sorry for this post here, but I don’t know where I can ask for it. I am looking for suitable dedicated server with high HDD volume and unlimited traffic.
I found: 
https://streaming-servers.com

I would ask you about the requirements, are those server okey ?

**Comment by rajohn007** [comment]
I think Its more than enough. Minimum requirement for Streama is 2GB RAM.

**Comment by ProTechEx** [comment]
Ok thanks mate
