### ISSUE TITLE
New Java Command needed

### ISSUE THREAD

**Issue by andrewfer000** [streamaserver/streama#742]
### Issue description
Java doesn't have a required module

### Steps to Reproduce

1. follow the install steps on Ubuntu 18.04.2 

### Expected Behaviour

The application should start

### Actual Behavior

Spits out java gibberish 
### Environment Information

FIX: The new command is
 java -jar --add-modules java.xml.bind streama-1.6.1.war 
Please update documentation to reflect this

- **Operating System**: Ubuntu 18.04.2
- **Streama version**: Latest
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: TODO
- **Container Version (If Applicable):** TODO

**Comment by andrewfer000** [comment]
This is for Java 9+ only

**Comment by dularion** [comment]
Oh cool, I didn't even know it worked at all with Java 9 😊

**Comment by andrewfer000** [comment]
Well It doesn't quite work. There are a few modules missing that I don't know about. It is very broken
