### ISSUE TITLE
Admin account lost privilege after logon name chnage

### ISSUE THREAD

**Issue by andrewfer000** [streamaserver/streama#743]
--------------------------------------------------------------------------------------------------------

### Issue description
Changing the admin username breaks admin access. if I use the admin URL the site breaks. along with access denied.

### Steps to Reproduce

1. Go to admin user settings
2. change the username
3. log out and in again

### Expected Behaviour

The username should change and still allow admin panel access

### Actual Behaviour

The admin username changes but admin panel is gone 

### Environment Information

- **Operating System**: Ubuntu 18.04 LTS (LAMP)
- **Streama version**: 1.6.0 (I use the built in database)
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: N/A
- **Container Version (If Applicable):** N/A

**Comment by andrewfer000** [comment]
I just decided to reset the DB file and start a new. Can someone explain to me (or send me a link) on how to setup Streama with MySQL so I can work with it easier.

**Comment by dularion** [comment]
thanks to @mcchan hopefully fixed in next release
