### ISSUE TITLE
 Leaving empty background breaks streama

### ISSUE THREAD

**Issue by CardealRusso** [streamaserver/streama#747]
{"message":"Internal server error","error":500}

**Comment by dularion** [comment]
How to you mean, leaving empty background?

**Comment by CardealRusso** [comment]
simply leave empty the loginBG at admin panel and save
after logout i got repeated 500 error and i had to export the db from mysql, manually enter any background then import db because i dont have any db manager

**Comment by dularion** [comment]
Thanks, ill check it out

**Comment by dularion** [comment]
Fixed, thanks to @mcchan1991

**Comment by dularion** [comment]
Here i also added some more null-checks: https://github.com/streamaserver/streama/commit/0d322bc9ed8be8ed5ba5a9422cad99211133ee83
