### ISSUE TITLE
Streama does not play hevec/x265 encoded video stream

### ISSUE THREAD

**Issue by ManuGithubSteam** [streamaserver/streama#750]
### Issue description

Videos who are encoded with HEVC/x265 will not be played back in streama. Audio works fine tho.
The video screen is just black.

### Steps to Reproduce

1. Get your hands on some hvec or x265 encoded movie
2. add to streama
3. try playback

### Expected Behaviour

See the video feed

### Actual Behaviour

Screen is black and sound is playing

### Environment Information

- **Operating System**: Ubuntu
- **Streama version**: 1.6
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: no custom build
- **Container Version (If Applicable):** No container.

How can i fix it ? do i just need to update the ffmpeg lib or something on the server ? Is ist a client issue ?

Thanks

**Comment by dularion** [comment]
This is an html5 video issue, x265 encoding is currently just not supported across browsers. 
See this table for reference: https://caniuse.com/#feat=hevc

**Comment by CardealRusso** [comment]
hevc works on my browsers and worked on streama
this dedpends on browsers
