### ISSUE TITLE
[Request] Option to disable video seek and resume of time

### ISSUE THREAD

**Issue by CardealRusso** [streamaserver/streama#751]
Option on admin panel to disable video seek and resume of time, start from 00:00 (still resume the episode)

Some video sources dont inform headers, so the video is downloaded with unknow size and because of this cant download partial files, breaking the video sek

**Comment by dularion** [comment]
I am not sure I get what you are referring to. arent all html5 compatible videos seekable? Why would you want to disallow this?

**Comment by CardealRusso** [comment]
no, depends on video source
for example: https://drive.google.com/uc?authuser=0&id=1Ppw1rrFqdSTQYKyuYC04EjRboIpecgSX&export=download

google drive links dont give file size, so you cant seek an unknow filesize

**Comment by dularion** [comment]
Oh I see. thanks for the example link. Makes sense to automatically disable it there, this can be checked in the backend.
