### ISSUE TITLE
Cant disable anonymous access after enabling

### ISSUE THREAD

**Issue by CardealRusso** [streamaserver/streama#760]
### Issue description
Cant disable anonymous access after enabling

### Steps to Reproduce

1. Enable anonymous access
2. Test anonymous access
3. Try to disable anonymous access

### Expected Behaviour

disable anonymous access

### Actual Behaviour

settin gs saves "sucessifly" after unchecking, but keep enabled after f5

### Environment Information

- **Operating System**: CentOS Linux release 7.6.1810 (Core)
- **Streama version**: streama-1.6.1
- **Container Version (If Applicable):** OpenVZ

**Comment by dularion** [comment]
I actually cant reproduce this.. please try again in the new release

**Comment by dularion** [comment]
https://github.com/streamaserver/streama/releases/tag/v1.6.2

**Comment by EmiPoN** [comment]
@CardealRusso Can you solved? Because I know how solve...
