### ISSUE TITLE
Features for "Outro Start"

### ISSUE THREAD

**Issue by CardealRusso** [streamaserver/streama#762]
Currently the "Other Start" option does not change anything. Does not make the video jump to the next.
Make him jump and make the "next-video-overlay" respect the "Other Start", which is currently displayed with 30 seconds left to finish the episode, continue displaying when there is 30 seconds remaining but respecting the "Other Start" if exists, "next-video-overlay" 30 seconds before "Other Start"

**Comment by dularion** [comment]
So I totally agree that the next-video-overlay should respect the outro-start time. However, I dont think the video should just auto-switch. But i can add that as an admin-option for those of us who might want such a thing. 

So I suggest to implement 2 things: 

1) make next-video-overlay show at outro-start if its set
2) make videos auto-skip to the next if outro-start is set, if it this enabled in the admin-settings. 

Agreed?

**Comment by CardealRusso** [comment]
wait a second, forcing auto skip is not very good because some movies/series have post-credit scenes

hm i think just respecting outro start is good for now, right?
make next-video-overlay 5 secs before outro-start if its set

**Comment by dularion** [comment]
sure

**Comment by dularion** [comment]
solved in https://github.com/streamaserver/streama/releases/tag/v1.6.2
