### ISSUE TITLE
Missing Docker instructions

### ISSUE THREAD

**Issue by SergioSV96** [streamaserver/streama#764]
- Can't find any docker or docker-compose installation instructions
- Is the Dockerfile ARM compatible? i.e. Raspberry Pi

**Comment by dularion** [comment]
Very true.. The core devs are not so deep into docker, so other people are maintaining that a bit. Maybe one of them can help you out. I would gladly add docker docs to out website once I get a hand on those myself ;)

**Comment by kerberjg** [comment]
@SergioSV96 the Dockerfile in use relies on the `openjdk:8-jre-slim` image, which is compatible with `arm32v7` (which is what you're looking for).

I'm not sure if we have multiarch builds of Docker on the Hub, but if you were to build a Streama Docker image yourself, it would run on ARM.

**Comment by kerberjg** [comment]
@dularion Do we have build (not install) docs for Streama somewhere? They'd be largely beneficial towards improving the dockerization, since the current Dockerfile seems to rely on preexisting builds

**Comment by dularion** [comment]
Actually, I dont think so now that you mention it... ill write one quickly

**Comment by dularion** [comment]
Here u go: https://github.com/streamaserver/streama/wiki/Manually-build-Streama-.war-file

**Comment by dularion** [comment]
So @l33tness contributed this wiki page. let me know if it helps you out: https://github.com/streamaserver/streama/wiki/How-to-use-Docker-image

**Comment by dularion** [comment]
let me know if you need any more help other than the wiki page
