### ISSUE TITLE
validateSettings(...).success() is not a function

### ISSUE THREAD

**Issue by greg6614** [streamaserver/streama#773]
### Issue description

Hi, I'm trying to deploy streama with docker but i'm not able to pass the first settings setup.
When i'm filling the base settings like "Upload Directory" nothing happens. When i take a look in the Chrome console i get the following error :

`TypeError: e.settings.validateSettings(...).success is not a function
    at c.a.validateSettings (streama.unminified.js:6863)
    at fn (eval at compile (vendor.unminified.js:29117), <anonymous>:4:645)
    at e (vendor.unminified.js:41650)
    at c.$eval (vendor.unminified.js:32092)
    at c.$apply (vendor.unminified.js:32191)
    at HTMLInputElement.<anonymous> (vendor.unminified.js:41654)
    at HTMLInputElement.dispatch (vendor.unminified.js:7620)
    at HTMLInputElement.m.handle (vendor.unminified.js:7433)
(anonymous) @ vendor.unminified.js:28266
(anonymous) @ vendor.unminified.js:24545
$apply @ vendor.unminified.js:32196
(anonymous) @ vendor.unminified.js:41654
dispatch @ vendor.unminified.js:7620
m.handle @ vendor.unminified.js:7433`

### Expected Behaviour

I think i should get a success or an error message.

### Actual Behaviour

Nothing happens and i get the previous stacktrace.

### Environment Information

- **Operating System**: Running on docker with java 8
- **Streama version**: Latest release : Streama V1.6.3

Thanks for your work and I hope we will be able to solve this issue

**Comment by dularion** [comment]
Oh thanks!

**Comment by dularion** [comment]
release can be found here: https://github.com/streamaserver/streama/releases/tag/v1.6.4

**Comment by greg6614** [comment]
Wow that was fast! Many thanks I will update my container!
