### ISSUE TITLE
[Windows] Unable to change logo

### ISSUE THREAD

**Issue by MrArca9** [streamaserver/streama#778]
### Issue description

Unable to change Logo

### Steps to Reproduce

1. Windows Installation
2. Chrome/Firefox (Both Tested)
2. Run Jar As Admin
3. Wait for server to start
4. Attempt to change logo using file selection

### Expected Behaviour

Logo should change, or some form of notification, or even an exception should be produce.

### Actual Behaviour

No logo change, no error, nothing.

### Environment Information

- **Operating System**: Windows 10
- **Installation Directory**: C:\StreamA (Successfully Validated In Browser)
- **Running As Admin**: True
- **Streama version**: 1.6.4

### Install Directory:

- \Data\<Empty>
- \application.yml
- \FA.png (Logo. Size: 38.5KB)
- \StartServer.bat
- \StreamA.jar
- \StreamA.mv.db
- \Streama.trace.db

### Log.txt Output:
INFO streama.Application - Starting Application on xxxxx with PID 5792 (C:\StreamA\StreamA.jar started by xxxxx in C:\StreamA)
DEBUG streama.Application - Running with Spring Boot v1.4.4.RELEASE, Spring v4.3.6.RELEASE
INFO streama.Application - The following profiles are active: production

Configuring Spring Security Core ...
... finished configuring Spring Security Core

INFO streama.Application - Started Application in 15.068 seconds (JVM running for 16.724)
Grails application running at http://localhost:8080 in environment: production

(EOF)

**Comment by dularion** [comment]
fixed in v1.6.5 https://github.com/streamaserver/streama/releases/tag/v1.6.5
