### ISSUE TITLE
Unable to verify Phone Number on the Discord

### ISSUE THREAD

**Issue by airsay** [streamaserver/streama#780]
So for months now, I've only been able to reading posts on the Discord app. I am unable to verify my phone number. I'm based in Nigeria and was wondering if there was some kind of restriction on phone verification outside the US

**Comment by CardealRusso** [comment]
your color skin is black?

**Comment by airsay** [comment]
Disregard

**Comment by CardealRusso** [comment]
Close this please

**Comment by bayuanderas** [comment]
Njirr

Pada tanggal Rab, 24 Apr 2019 19.43, CardealRusso <notifications@github.com>
menulis:
