### ISSUE TITLE
Link to getting started in current README.md is out-of date

### ISSUE THREAD

**Issue by ohcfe** [streamaserver/streama#781]
### Issue description
Link to getting started in current README.md is out-of date

### Steps to Reproduce

1. Look at README.md
2. Follow the link to "Installation and first time setup" (https://github.com/streamaserver/streama/wiki/Getting-started)

### Expected Behaviour

The link should take us to the current instructions for getting started with the repository we have cloned. Better would be to link to the relavent documentaiton internally in the repository which was cloned.

### Actual Behaviour

https://github.com/streamaserver/streama/wiki/Getting-started  says:

"""
Getting started
EditNew Page
Hannah Ryan edited this page on 24 Sep 2018 · 24 revisions
This is out of date, please see https://streamaserver.org/docs
"""

### Environment Information

- **Operating System**: Arch linux
- **Streama version**:  1.6.5 (commit 81ab64dadfd0127889962eb079da044c52a44233)

**Comment by HannahRy** [comment]
Fixed!
