### ISSUE TITLE
[BUG] Error when trying to add a 11th TAG

### ISSUE THREAD

**Issue by Sidefix** [streamaserver/streama#782]
### Issue description
Adding custom TAGS for videos works as intended, until attempting to add a 11th tag. When adding a 11th tag, an error pops in the UI, with an error in the log as well.
See attached log for stack trace.
[Streama_10th_tag_save_error.log](https://github.com/streamaserver/streama/files/3113926/Streama_10th_tag_save_error.log)

### Steps to Reproduce

1. Add or edit existing movie
2. Select the Tag field
3. Type in a new name for a non-existent tag (10 tags must already exist at this point)
4. Save movie

### Expected Behaviour

The tag should be added and the movie should be saved successfully

### Actual Behaviour

Error in UI and in logs
Movie does not save

### Environment Information

- **Operating System**: Ubuntu 18.04.1
- **Streama version**: 1.6.5

**Comment by Sidefix** [comment]
Updated info; I was mistaken, and 10 Tags have to exist for the issue to occur.

In addition, I have also edited the streama.mv.db with H2 to see the tags myself, and it turns out that the tags I was trying to save, **ARE** getting saved, they just aren't showing up in the UI.

**Comment by dularion** [comment]
Ok so i fixed something here, but I dont think it was your issue directly. Maybe retest on v1.7.0 when thats stable. 
Thanks!
