### ISSUE TITLE
Bug in TV-shows

### ISSUE THREAD

**Issue by AdrianB1992** [streamaserver/streama#787]
## Issue description

When I create a TV-Show and add the poster, the TV-Show appears duplicated in streama.

### Steps to Reproduce

1. Create new TV-Show.
2. Upload poster for TV-Show.

### Expected Behaviour

I should create only one TV-Show

### Actual Behaviour

When I create the TV-Show and add the poster, the TV-Show appears in streama duplicated.

### Environment Information

- **Operating System**:  Ubuntu 18.04 LTS
- **Streama version**: 1.65

**Comment by dularion** [comment]
Stupid question: but where exactly can you adjust the poster image for tv-shows? in the "Edit Info" popup? I cant see it at least... 
Are you adding tv-shows manually or via tmdb?

**Comment by dularion** [comment]
nvm, found the bug and fixed it. Thanks for reporting!

**Comment by dularion** [comment]
(will be part of v1.6.7)
