### ISSUE TITLE
Cant delete listings in 'Other Videos'

### ISSUE THREAD

**Issue by dly2424** [streamaserver/streama#795]
### Issue description
When trying to delete a video listing in 'Other Videos' It does not delete. This persists through refreshes, restarts and relogins.

### Steps to Reproduce

1. Go to Manage Content - Other Videos
2. Create generic video
3. Click video
4. Try to delete video

### Expected Behaviour

Video should be deleted

### Actual Behaviour

Video is not deleted

### Environment Information

- **Operating System**: Ubuntu mate - Linux
- **Streama version**: 1.7.0-RC6 (unstable)
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: Not Applicable
- **Container Version (If Applicable):** Not Applicable

### Notes

Sorry for creating so many issue listings, just trying to document the errors i am finding.
See attached gif:
![test5](https://user-images.githubusercontent.com/46138781/57525091-c50d9100-72f7-11e9-998b-5a2ab63c3ada.gif)

Using an admin account i created in streama, not the default admin account, all permissions are given.

**Comment by xRedZoid** [comment]
The Other videos you created is deleted, it just shows that library but in normal database, It's 100% deleted just not removed from User Client Side. As you can see in your Dashboard. It won't show will be fixed in future updates!

**Comment by dularion** [comment]
Fixed in 1.10 :)
