### ISSUE TITLE
[Critical] Cannot create new movies as of 1.7.0 RC6

### ISSUE THREAD

**Issue by Sidefix** [streamaserver/streama#798]
### Issue description
Cannot create new movies on 1.7.0 RC6

### Steps to Reproduce

1. Go to Manage Content
2. Go to Movies
3. Hit Create New Movie
4. Complete required fields and hit Save

### Expected Behaviour
The newly defined movie should be saved successfully with no errors

### Actual Behaviour
"An internal error" message appears in the Streama UI, and the attached error appears in the log

### Environment Information

- **Operating System**: Ubuntu 18.04.1
- **Streama version**: 1.7.0-RC6
[Streama_rc6_bug.log](https://github.com/streamaserver/streama/files/3171426/Streama_rc6_bug.log)

**Comment by Sidefix** [comment]
I did not try in RC5, but it did work in RC4 and earlier

**Comment by dularion** [comment]
True, fixed in RC7

**Comment by dularion** [comment]
https://github.com/streamaserver/streama/releases/tag/v1.7.0-RC7
