### ISSUE TITLE
Bug: Accents in Dashboard Search cause issues

### ISSUE THREAD

**Issue by Ircas** [streamaserver/streama#799]
It seems that search needs some sort of Enhancement or Bug Fix I don't really know.
So this might not affect the 90% of users of streama but I think it's a big deal for non english languages.

**Issue:**
When a title from an imported video has accents like ( š ά é ñ  í ü ï ) you have to search using the accent, if not no results show up.

**How it should work**
When using other searches lets say directly in sql (phpmyadmin) it doesnt matter if you use accents or not the results will come up. 
Lets say we search for Jörn it doesnt matter if we search for Jörn or Jorn it will come up as the same.

**Possible solutions - Helpfull Links**
Search should match accented characters (those with diacritical marks). 
I have searched the internet and found a bunch of stuff that might be helpfull.

-- This is called Accent Folding in autocomplete (jQuery).
https://jqueryui.com/autocomplete/#folding

-- Following a very nice article with code about this.
http://alistapart.com/article/accent-folding-for-auto-complete/

-- Here is an actual fiddle on how this should work
http://jsfiddle.net/cps7/3R5B2/7/

-- Finally this is a website you can use (type) and see all accented letters from 25+ languages
https://czech.typeit.org/

P.S. If you have time to look into this It would be really nice for a further Enhancement in search. The idea is simple. Just GET the original title from TMDB API and store it in the database. 
So when you either search with your "localized" title or the original one the video will show up in both cases.

**Comment by dularion** [comment]
Could you give me an example of a name with an accent?

**Comment by dularion** [comment]
Ok, the main issue is fixed in 1.7.0-RC8. For the addition at the end, please open a separate feature request :)

**Comment by Ircas** [comment]
Any localized movie when using other language from TMDB lets say :

https://www.themoviedb.org/movie/15383-l-arm-e-des-ombres

Original title is L'Armée des ombres (with an accent e)
English title is Army of Shadows


An other example 

https://www.themoviedb.org/movie/120-the-lord-of-the-rings-the-fellowship-of-the-ring?language=en-US

English title 
The Lord of the Rings: The Fellowship of the Ring

Thats the title in Hungary
A Gyűrűk Ura: A gyűrű szövetsége

If I am using a TMDB other than english that has accented letter it imports if possible the localized title. 

If you start searching you have to add every accent for the movie to show up as a result.

By grabbing and storing both original title and localized one then edit the search to match accented letters on both video titl it would not matter how you search the movie it would alway show up.

**Comment by dularion** [comment]
as i said, already fixed in RC8 :) see https://github.com/streamaserver/streama/releases/tag/v1.7.0-RC8

**Comment by Ircas** [comment]
Sorry was too let on reply I will check the update then I will ask you to Mark as resolved.
