### ISSUE TITLE
[Feature Request] More edit options in admin panel

### ISSUE THREAD

**Issue by Ircas** [streamaserver/streama#800]
As streama is growning and getting even more popular I would like to see a couple of edit options added while editing a file.

1) 
Because all of the metadata is pulled directly from TMDB some info might be missing like the trailer.

I would like to have a button to either add or edit the youtube video (trailer) directly through an edit button

2)
I would like to have again a button to edit the date of upload. 
This way If I would like to show the movie on the first page without making a highlight I could add a later date

The edit buttons are endless other ideas are having a way to edit/add/delete ALL metadata that gets pulled from TMDB (actors,creators etc..) but the 2 I am more concerned are the above.

Especially the 1st one about the youtube trailer.

**Comment by dularion** [comment]
worked on your issue. hope that it does what you want it to do: https://github.com/streamaserver/streama/releases/tag/v1.7.0-RC10
