### ISSUE TITLE
Can't add local files

### ISSUE THREAD

**Issue by kaysond** [streamaserver/streama#807]
### Issue description
Adding a matched file gives `TheMovieDB Error: not all files were added unfortunately. This is due to TheMovieDB API LIMIT constraints. Just try again in a couple of seconds :) ` despite waiting for plenty of time.

Java log shows:
```
May 23 13:35:55 fserver java[31134]: DEBUG grails.app.services.streama.TheMovieDbService - conn.responseCode: 200
May 23 13:35:57 fserver java[31134]: ERROR grails.app.services.streama.TheMovieDbService - Error occured while trying to retrieve data from TheMovieDB. Please check your API-Key.
```

### Steps to Reproduce

1. Install streama
2. Bulk create from files
3. Run matcher on single file
4. Wait 10s (let tmdb rate limit expire)
5. Click Add this File

### Expected Behaviour

File should be added

### Actual Behaviour

Error as above

### Environment Information
Running via systemd

- **Operating System**: Ubuntu 18.04.1
- **Streama version**: v1.7.0-RC10

**Comment by dularion** [comment]
the files that failed should have a little info-icon with some more info to them. Can you please check that and paste it here?

**Comment by kaysond** [comment]
![image](https://user-images.githubusercontent.com/1147328/58285406-8ea52c80-7d61-11e9-91ef-15618b8e4e23.png)

**Comment by kaysond** [comment]
There's no additional information from the ? icon

**Comment by dularion** [comment]
There is no info if you hover over the questionmark? (maybe need to hover a lil longer?)

**Comment by kaysond** [comment]
Nope! The DOM element has no title attribute, and there are no event handlers attached.

I do get this popup
![image](https://user-images.githubusercontent.com/1147328/58285828-623de000-7d62-11e9-82c6-49b01312ca6d.png)

**Comment by dularion** [comment]
hm that is strange. 
That blue message is outdated, it blames everything on the API limit but I don't think thats the case for you. if it were, it would show up as a title tag for the questionmark. 
hm... and you configured an API Key?

**Comment by kaysond** [comment]
I did configure the API key, and the log shows HTTP 200 responses. I also tested the API key just by accessing a url on my browser and that works fine...

**Comment by kaysond** [comment]
Here's the JSON response from the `file/matchMetaDataFromFile.json` request:
```
[{"file":"/var/www/files/Video/TV Shows/Test/Luther.S05E01.Episode 1.Bluray-1080p.mkv","type":"episode","tvShowOverview":"A dark psychological crime drama starring Idris Elba as Luther, a man struggling with his own terrible demons, who might be as dangerous as the depraved murderers he hunts.","tvShowId":1426,"showName":"Luther","poster_path":"/hDxOMX8zzH1FiqKWVBzNaYGBkle.jpg","backdrop_path":"/A2qdFRq9oJDC5E7fbgSS4POUMDF.jpg","apiId":1626346,"episodeName":"Episode 1","first_air_date":"2019-01-01","episodeOverview":"A new spate of nightmarish murders brings DCI John Luther to once again face the depths of human depravity on the streets of London. As the body count rises, and gangster George Cornelius applies his own pressure, can Luther catch the killer and save his own neck?","still_path":"/yV6c9zk4g5yADpIa55mozcdEc9O.jpg","status":1,"message":"match found","season":5,"episodeNumber":1}]
```

And the `file/bulkAddMediaFromFile.json` response:
```
[{"first_air_date":"2019-01-01","showName":"Luther","episodeOverview":"A new spate of nightmarish murders brings DCI John Luther to once again face the depths of human depravity on the streets of London. As the body count rises, and gangster George Cornelius applies his own pressure, can Luther catch the killer and save his own neck?","episodeName":"Episode 1","still_path":"/yV6c9zk4g5yADpIa55mozcdEc9O.jpg","type":"episode","message":"match found","tvShowId":1426,"episodeNumber":1,"poster_path":"/hDxOMX8zzH1FiqKWVBzNaYGBkle.jpg","backdrop_path":"/A2qdFRq9oJDC5E7fbgSS4POUMDF.jpg","file":"/var/www/files/Video/TV Shows/Test/Luther.S05E01.Episode 1.Bluray-1080p.mkv","tvShowOverview":"A dark psychological crime drama starring Idris Elba as Luther, a man struggling with his own terrible demons, who might be as dangerous as the depraved murderers he hunts.","season":5,"apiId":1626346,"status":4}]
```

In case that helps... seemed odd that theyre identical except the status

**Comment by dularion** [comment]
might have something to do with my recent changes for subtitle-matching... I'll try to reproduce by creating a test-file `Luther.S05E01.Episode 1.Bluray-1080p.mkv`

**Comment by nihakue** [comment]
I have the exact same problem, could it have anything to do with this?

I am trying to add a tv show, but I noticed this log line: 
```
WARN grails.app.services.streama.TheMovieDbService - could not load fullMeta for Movie this time, https://api.themoviedb.org/3/movie/null?api_key=197bf1a762d8e13a072c32e85213737d&language=en                                                                                                                                                        ERROR grails.app.services.streama.TheMovieDbService - Error occured while trying to retrieve data from TheMovieDB. Please check your API-Key.   
```

Looks like you're possibly hitting the wrong endpoint / pulling `movieId` off of the previous response when you should be using `tvId` or `showId` or whatever it is for TV shows.

**Comment by kaysond** [comment]
@dularion any luck? I don't think it has to do with the file name. It fails the same way for all my files

**Comment by Ircas** [comment]
I do have issue with this too. 
Confirming this happends only with tv shows...

Hope we can have a hotfix as soon as possible...

**Comment by dularion** [comment]
Weird, more and more people are chiming in on this, but i cant reproduce it for the life of me. I will try creating some files on the demo-server and send you a link

**Comment by dularion** [comment]
Ok, check it out here: https://demo.streamaserver.org/#!/admin/shows
![image](https://user-images.githubusercontent.com/936076/58504312-97936500-818a-11e9-822e-1a9e6f486766.png)

Seems to work fine there ...

**Comment by kaysond** [comment]
No it doesn't ;)
https://imgur.com/a/xhuld8f

My exact clicks are:

1. Bulk Create From Files
2. tv-shows
3. shameless-s08
4. checkbox next to s08e01
5. run matcher
6. add file under match: shameless s08e01

Running firefox 67. I did try MS Edge with my own setup and it didn't work either.

**Comment by Ircas** [comment]
@dularion did you try to press add all matched or even on 1 add this file?

**Comment by dularion** [comment]
aaah see, that I didnt do! Finally I can reproduce it. Will probably have a fix for you later tonight :)

**Comment by dularion** [comment]
Alright guys, hope it works: https://github.com/streamaserver/streama/releases/tag/v1.7.0-RC11

**Comment by kaysond** [comment]
Fixed! Thank you
