### ISSUE TITLE
[Bug]Imdb link on tv shows

### ISSUE THREAD

**Issue by Ircas** [streamaserver/streama#810]
I am using latest v1.7.0 rc11.
When I add by bulk a tv show (thanks for the fix btw @dularion) everything goes smooth.

The show is created the seasons and episodes are auto populated and everything works as expected. 

But when I press the (i button) to open the tv shows details and click on the imdb link it has not been populated.

The link is shown as http://www.imdb.com/title/
As a result if you click on the link you get a 404 not found on imdb

If i add it manually (the imdb id) it works.
This seems to happen only on tv shows. 

P.S while you are working on details a good idea is to have the tmdb link show up somewhere maybe under imdb. 

P.S2 As previously requested I would like have the original title shown somewhere in video details (i icon) and make it searchable too from dash, reference to issue #803

**Comment by dularion** [comment]
Good catch, Fix will be in the next release
