### ISSUE TITLE
[Bug/issue] Mobile responsive, no sort/filter

### ISSUE THREAD

**Issue by Ircas** [streamaserver/streama#811]
Sorry for not following the template but this doesnt have to do with a partucular version of streama or server setup. 

So the issue here is when using mobile browser in portrait mode the sort, filter by genre, search by name section is hidden. If this is intentional please close this ticket.

While in landscape mode this is shown perfectly. 
I have attached a couple of img to further understand my concern. 
I believe there is enough space to add at least the sort button. 

Portrait mode 

![Screenshot_20190529-151039_Chrome](https://user-images.githubusercontent.com/50799513/58557437-13db8600-8227-11e9-9a76-1584183de08d.jpg)

Landscape mode 

![Screenshot_20190529-151026_Chrome](https://user-images.githubusercontent.com/50799513/58557500-32418180-8227-11e9-8be2-c44659bf7029.jpg)

**Comment by dularion** [comment]
Not sure why it wasnt there for mobile - added it now.
