### ISSUE TITLE
[Feature Request] Add download button on Season page

### ISSUE THREAD

**Issue by kaysond** [streamaserver/streama#812]
I have a few shows that I've added locally but are mkv's so they can't be played. The client shows an error message, but never gives me an opportunity to download the file. So it would be nice if in the episode selection page, there was a button for downloading!
![image](https://user-images.githubusercontent.com/1147328/58585741-59d82000-820e-11e9-9baf-ed77cb94c926.png)

**Comment by Norwelian** [comment]
All my files (a lot xD) are MKV and play fine, the problem must be in one of the codecs, either audio, video, or both, try re-coding them to x264+AAC, that codec combo works for most browsers.
Appart from that, yeah, it's a good idea to have the download button option available!

**Comment by kaysond** [comment]
Ah you're right about that. It's DTS audio.

Nonetheless the option would be nice!

**Comment by dularion** [comment]
Cool feature, added it :)

**Comment by kaysond** [comment]
wow youre fast!
