### ISSUE TITLE
[Missing code] Order User Video Activity by updated date (#808)

### ISSUE THREAD

**Issue by Norwelian** [streamaserver/streama#814]
First of all, I'm sorry about opening another issue... But I couldn't reopen the other one (I think that's because I didn't close it).
I tested the code that solved #808 and it doesn't work, even though the drop-down menu appears, and it's perfect. You can change the filter, but nothing happens.
But, and correct me if I'm wrong, I think the workflow with the changes @dularion made works as follows:
First, when you change the filter in the web, `onSortChange()` gets called (in `settings-user-activity.js`), which calls `loadList()`, which in turn calls the `apiService` with some parameters, including the `currentSort`.
Then, the `apiService` (in `api-service.js`) returns the result of a `GET` request made to `userActivity.json` (whose code is in `UserActivityController.groovy` I think) and then the list is actually made and returned.
The only thing that I think is missing is that we don't actually handle the sorting in `UserActivityController.groovy`, and that's why nothing happens when you change the filter, even though the code @dularion added works as expected.
Hope it's of some help, and, as always, thanks for the quick response and good work!!

**Comment by dularion** [comment]
weird, i did add that part yesterday, but its gone today... 🤷‍♀ 
ill push and rebuild

**Comment by dularion** [comment]
give it a try now: https://github.com/streamaserver/streama/releases/tag/v1.7.0-RC13

**Comment by Norwelian** [comment]
Now it works perfectly!!
Thank you very much, @dularion !
