### ISSUE TITLE
Subtitle size change fails

### ISSUE THREAD

**Issue by iBuaSpaz** [streamaserver/streama#816]
### Issue description
subtitles size cannot be changed in web player

### Steps to Reproduce

1. open movie
2. change subtitle
3. hit size buttons and then okay

### Expected Behaviour
bigger subtitles or smaller

### Actual Behaviour
Does nothing

### Environment Information
- **Operating System**: Ubunto
- **Streama version**: v1.7.0-RC13

**Comment by iBuaSpaz** [comment]
Its i issue on my 4k monitor, subtitles are really small :)

**Comment by NoFrosty** [comment]
Same issue for me.

Operating System: Windows Server
Streama version: v1.7.0-RC13 (but edited)

**Comment by dularion** [comment]
will be fixed in 1.7.0 stable release
