### ISSUE TITLE
[Feature request]Download button on movie/other video details

### ISSUE THREAD

**Issue by Ircas** [streamaserver/streama#818]
After reading about the mkv issue and how you added a download button I was thinking if its possible to do the same for all movies and other videos.

So the idea is that next to the actual play button in video details to add maybe a download button.

This will elliminate the need to actually open the movie/player then click on the download button.

2 buttons 2 options. Play or download.

Assuming this is a Quick fix and more people want it I hope it gets added soon.

**Comment by kaysond** [comment]
+1. Just ran into this. @dularion any chance for a quick fix? Like #812

**Comment by Ircas** [comment]
This has been resolved as 1.7.2
https://github.com/streamaserver/streama/releases/tag/v1.7.2

I am closing this ticket... Thanks @dularion
