### ISSUE TITLE
deploy to live/production server

### ISSUE THREAD

**Issue by jaynelim** [streamaserver/streama#825]
if anyone needs help to deploy streama to a live server, i can help.

**Comment by fazlerabbi37** [comment]
@jaynelim why don't you put the instructions on a production.md and create a pull request to this repo. I am sure all of us will be able to benefit from it. :smile:

**Comment by denny64** [comment]
@jaynelim Do you have any instructions? :)

**Comment by black-wolf8** [comment]
@jaynelim can u upload the instruccions?? i need help

**Comment by blackhat84** [comment]
i m new in coding can u hel wit the live server pls

**Comment by banha-serhii** [comment]
No one find instructions for deploy?

**Comment by dularion** [comment]
sure, check here https://github.com/streamaserver/streama/wiki/Running-as-a-service-(autostart)-on-Ubuntu-15-or-higher

**Comment by dularion** [comment]
or this https://github.com/streamaserver/streama/wiki/Full-streama-setup-on-a-clean-Ubuntu18-with-mysql,-system.d-&-letsencrypt
