### ISSUE TITLE
Genre not work in  Version 1.7 

### ISSUE THREAD

**Issue by rn2020** [streamaserver/streama#830]
HI 
Genre not work in  Version 1.7 yet Might be something broke 

Best

**Comment by dularion** [comment]
I cant reproduce this on the demo, i just upgraded it to 1.7 https://demo.streamaserver.org. 

What exactly are u doing where genre dont show up? When i simply manually create a movie (without any fancy stuff) it works just fine

**Comment by Grisu118** [comment]
Your right, it works now. For me the problem was in the movie creation, genre stayed empty.

Eventually this was a temporary problem on theMovieDb.org

**Comment by dularion** [comment]
Possibly. Did you restart since then? During startup it adds all missing genre automatically as well, which might have solved it for you. But I prefer that it works right away.

**Comment by rn2020** [comment]
thanks alot Dularion and  Grisu118 that solved the issues
