### ISSUE TITLE
[Issue] Fullscreen button

### ISSUE THREAD

**Issue by xRedZoid** [streamaserver/streama#833]
Fullscreen button broken, Tried on these platforms

Linux
Android
IOS
Windows

Button does not function,

**Comment by Ircas** [comment]
I think you have sort of problem with your browser or addon.

Been using streama for over 6 months now never ever had a problem with full screen. 

Please open a correct issue using example template. What version are you using. Is the server on windows or Linux sql or integraded db and what steps do you make to reproduce issue.

Unless you edit this post it will be closed for not following rules.

**Comment by xRedZoid** [comment]
The fullscreen has been tested in all platforms. It does not work, i have tried other browsers but the fullscreen button does not function except if you press ( F11 ) to fullscreen
