### ISSUE TITLE
[Issue] IOS Login

### ISSUE THREAD

**Issue by xRedZoid** [streamaserver/streama#834]
New issue, logging in with any IPhone will not work, the page will only refresh.

Working with Linux/Windows/Android - Hope IPhone users will be able to log in with the next update

**Comment by Ircas** [comment]
Please use some sort of a good browser when using streama. Not broken safari or edge. (you know that latest safari cannot load even Apple's website?) 

Try downloading chrome for ios and then login. Never had an issue before. Chrome is chrome for whatever device.

**Comment by xRedZoid** [comment]
Ircas, i have done the Nginx reverse proxy, it doesn't remove the port of 8080

**Comment by lclc98** [comment]
If you use nginx reverse proxy, it should remove the port 8080 from your url

**Comment by xRedZoid** [comment]
I did remove the 8080 port from my url, but whenever i want it to redirect to Streama website. it goes to welcome to nginx! instead
