### ISSUE TITLE
Black Screen for MKV Files

### ISSUE THREAD

**Issue by xRedZoid** [streamaserver/streama#837]
Hello, another issue we have here.

Does not show Screen, Black Screen

But sounds are working. MKV Support?

Does not also detect subtitles for other

**Comment by Norwelian** [comment]
https://github.com/streamaserver/streama/issues/828

**Comment by xRedZoid** [comment]
Alright thanks for the info! I just converted my whole MKV files with FFMPEG

**Comment by Norwelian** [comment]
I'm glad you could understand it and make it work ! :smiley:
