### ISSUE TITLE
[BUG] Subtitles with special characters do not display correctly

### ISSUE THREAD

**Issue by Sidefix** [streamaserver/streama#840]
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
### Issue description
Subtitles in foreign languages are displayed with unknown characters. I've attempted to change the system and browser locale, with no success. Screenshot attached.

Tested with:
- Chrome
- Edge
- Firefox

All browsers tested on Windows and Linux

Issue has been present for as long as I've been using Streama (circa 1.6.1). Have not tested with older versions.

### Steps to Reproduce

1. Load movie with SRT in foreign language (Romanian tested)
2. Load Romanian SRT in movie
3. Play

### Expected Behaviour
Special characters should display as intended in their native language

### Actual Behaviour
Unknown characters displayed in place of special characters

### Environment Information

- **Operating System**: Ubuntu 18.04.1
- **Streama version**: 1.7.0 stable

Related issue: #337 

![image](https://user-images.githubusercontent.com/26040103/60975110-0809d600-a334-11e9-8810-483574ad9aea.png)

Actual text from attached image:
"e c**ă**utat pentru crim**ă** **ș**i tr**ă**dare"

**Comment by Ircas** [comment]
Try the following.

Open srt with windows notepad. Go to file save as and be sure that encoding is set as utf8 and not ansi. Save the file and try again with streama.

I usually hard embed my srt so that when someone downloads the video subs always display properly. 

I hope this was the solution to your problem.

**Comment by dularion** [comment]
let us know if this did not work for you @Sidefix
