### ISSUE TITLE
Extremely slow loading after restart

### ISSUE THREAD

**Issue by omegasupreme3** [streamaserver/streama#845]
### Issue description
After each restart of the StreamA application, it takes minutes (e.g. 5 minutes or so) before it comes accessible again. During this time trying to access it through the webbrowser will fail giving time out error messages. However StreamA is running ("Grails application running at http://localhost:8080 ..." is in the log) and I can confirm that the port 8080 is actually open (using _netstat_). After those approx. 5 minutes have passed, everything seems ok and StreamA responds quick.

- No exceptions are shown
- The PC doesn't show heavy load (< 10% CPU load) and not much disk access is going on
- There is also more than enough physical memory free (800MB, system has 2GB) and the swap is hardly used.

### Steps to Reproduce

1. Restart the PC or the application
2. Wait until StreamA is running ("Grails application running at http://localhost:8080 ...")
3. Use **any** browser to access StreamA

### Expected Behaviour
I would expect that after StreamA is initialized I can access it. A bit slow for some moments is acceptable I think, because it might still do some stuff in the background.

### Actual Behaviour
After initialization I have to wait **at least** 5 minutes before I can access it. I suspect it has something to do with a network connection timing out. I have observed that behavior more often in the past when developing Java applications.

### Environment Information

- **Operating System**: CentOS 7 / Ubuntu 18.04. Both clean installations with nothing additional installed. In case of CentOS I checked SELinux, but no indications are there
- **Java version**: java-1.8.0-openjdk
- **Streama version**: 1.7.0/1.7.1

**Comment by omegasupreme3** [comment]
Would it be possible to turn on (verbose) logging for StreamA?

**Comment by xRedZoid** [comment]
The cause of slow startup could be Low Write/Read Disk on your VPS/PC/VM

**Comment by omegasupreme3** [comment]
Thank you for your suggestion, but I doubt it. It is running on a SSD, read-throughput is around 500MB/s, writes are a bit slower of course. Everything runs blazing fast, except the first part of the application initializing. Also note that if disk I/O would be an issue, I would see the CPU wait state go up which is not the case. I still do suspect network connection timing out to be the cause.

**Comment by xRedZoid** [comment]
Have you tried Restarting your Ubuntu/CentOS? & Not only Streama?

**Comment by xRedZoid** [comment]
Try sudo apt-get update to update your files that are not Latest

**Comment by omegasupreme3** [comment]
Yes I tried restarting the PC and all the software is completely up-to-date. I would like to add that as soon as the "slow" period of approx. 5 minutes has past, StreamA is quick as lightening.

**Comment by xRedZoid** [comment]
Well it's just startup, this isn't much of an Issue xd

**Comment by xRedZoid** [comment]
It's more like when you plug in your PC when you woke up and ate breakfast, it'll take a while

**Comment by omegasupreme3** [comment]
I am not realy sure if we do understand eachother about what is the issue here ;-) . So it is completely normal for StreamA to take approx. 5 minutes to fully startup? Even with a completely empty database? Just to be clear:

- During this period of 5 minutes the CPU load is about 2 or 3% during this period, so it is just idle. The CPU is a 4590 in case you might think it is some kind of low end CPU

**Comment by Ircas** [comment]
The only way to find out what is happening is debug streama while it starts. 

On my setup it takes about the same time to start functioning. But it doesnt brother me as streama restarts only on updates or server restart.

My server has the following specs:
CPU : Intel X3440 4c/8t @ 2.53 GHz
RAM : 8 GB
HDD : 12 TB HDD @7200rpm
Network : 1 Gbps up/down
Traffic : 100TB

I have like 2000 movies and 100 tv shows
But this is with only 5-10 people using it at the same time.

Latest 1.7.2 seems to be faster when starting dont know why. 

System load is at 5% cpu 10% ram

Hope I helped as much as possible maybe @dularion could help more

**Comment by omegasupreme3** [comment]
Thank you for your reply and your insight! I think it is also helpful to know that people experience more or less the same. With 2000 movies and such I can imagine that it takes a while, but in my case it also happens with an empty database.

Anyway it is not really a big issue I guess, but as a developer I find the behavior kind of odd if you take into account the context I described in the 1st post. Guess it is more of a hardcore dev thingy ;-) .

**Comment by dularion** [comment]
try increasing the ram on startup! 
one way to do it is to create a config file with the same name as your jar file, for example:
```
streama-1.7.0.jar
streama.jar -> streama-1.7.0.jar
streama.conf
application.yml
```
(in this example streama.jar is a symlink to a versioned streama file, and you start the streama.jar)
and in your `streama.conf` you have this setting: 
```
JAVA_OPTS="-server -Xmx4g -Xms512m"
```

or you can increase the ram even more! 
some times slow startup / loading time can mean that the java process reaches is max ram and has to garbageCollect like crazy

**Comment by omegasupreme3** [comment]
That makes totally sense! I will try this in the evening and let you know if it helps.

**Comment by omegasupreme3** [comment]
So it definitely helps to increase memory! I have to figure out with exactly what parameters so the startup time is acceptable. I set Xmx to 1G to see the effect, well took StreamA 20 minutes to come up and running. Setting it to 2G cut this down to 15 minutes.

Thank you for your help and quick response.

**Comment by omegasupreme3** [comment]
Reopening this issue.

I had to restart the PC after I added additional memory to test some configurations with the JVM, but it looks like starting up StreamA is getting worse the more movies I add. I already added 4GB to the system (of which 2GB is not used at all). All the remarks I made in the opening post about the CPU being idle, no disk I/O is still valid etc.

I really would like to know what is going on within StreamA. Is there a possibility to turn on verbose logging for StreamA?

(Btw thank you for this great application!)

**Comment by omegasupreme3** [comment]
Ok I gave this a spin on Windows and there it is starting literaly in seconds ... To be continued.

**Comment by omegasupreme3** [comment]
Closing this issue. Decided to write my own VOD so I can tailor it to my needs and situation. Nevertheless, you have a great looking system here and as a senior developer I can tell how much work you already put into it. This is something most people do not have a clue about, so I hope you get some donations to keep you going.

**Comment by bookmebus** [comment]
> ### Issue description
> After each restart of the StreamA application, it takes minutes (e.g. 5 minutes or so) before it comes accessible again. During this time trying to access it through the webbrowser will fail giving time out error messages. However StreamA is running ("Grails application running at http://localhost:8080 ..." is in the log) and I can confirm that the port 8080 is actually open (using _netstat_). After those approx. 5 minutes have passed, everything seems ok and StreamA responds quick.
> 
> * No exceptions are shown
> * The PC doesn't show heavy load (< 10% CPU load) and not much disk access is going on
> * There is also more than enough physical memory free (800MB, system has 2GB) and the swap is hardly used.
> 
> ### Steps to Reproduce
> 1. Restart the PC or the application
> 2. Wait until StreamA is running ("Grails application running at http://localhost:8080 ...")
> 3. Use **any** browser to access StreamA
> 
> ### Expected Behaviour
> I would expect that after StreamA is initialized I can access it. A bit slow for some moments is acceptable I think, because it might still do some stuff in the background.
> 
> ### Actual Behaviour
> After initialization I have to wait **at least** 5 minutes before I can access it. I suspect it has something to do with a network connection timing out. I have observed that behavior more often in the past when developing Java applications.
> 
> ### Environment Information
> * **Operating System**: CentOS 7 / Ubuntu 18.04. Both clean installations with nothing additional installed. In case of CentOS I checked SELinux, but no indications are there
> * **Java version**: java-1.8.0-openjdk
> * **Streama version**: 1.7.0/1.7.1

The same to me. I set it as a service in Ubuntu Server 16.04 and I checked the system control status confirm the app running with localhost:8080.

**Comment by omegasupreme3** [comment]
I guess you can better create a new ticket for this issue. I closed this one, because I don't need a fix anymore since I decided to go a different direction.
