### ISSUE TITLE
Incorrect Episode String in Video Activity

### ISSUE THREAD

**Issue by kumitterer** [streamaserver/streama#849]
### Issue description

In the Video Activity page, incorrect episode strings are displayed for the watched videos.

### Steps to Reproduce

1. Go to "Admin" in top navigation
2. Go to "User Activity" in side bar
3. Select "Video Activity" tab

### Expected Behaviour

Correct episode strings should be displayed (i.e. s{SEASONNUM}e{EPISODENUM}).

### Actual Behaviour

Incorrect episode strings like s{EPISODENUM}e{SEASONNUM} are displayed.

![image](https://user-images.githubusercontent.com/5702298/61937280-cbbeb280-af8e-11e9-946c-7ab442a9269c.png)

Additionally, for movies "sundefinedeundefined" is displayed.

![image](https://user-images.githubusercontent.com/5702298/61937335-edb83500-af8e-11e9-8afe-dd0561b9f852.png)

### Environment Information

- **Operating System**: Ubuntu 19.04
- **Streama version**: 1.7.2

**Comment by Ircas** [comment]
I can verify this issue too. Nice catch @kumitterer
