### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by peterpt** [streamaserver/streama#864]
I am using the latest version of streama 1.7.2 .
The first entry in database in field "other videos" is not ok here , not matter if i try to delete it or change the filename in it i am always without success .
This means that file is not registered in database when i upload it , but all other data is there , like the picture to that field and etc ....
When i try to delete it says ok but in reality is not ok , it is still there and dont get out .

I want to know where is database stored (is those .db files next to jar executable?) and how to open it ro remove that entry manually .
How can i open the database / or how can i delete that entry manually , because by the web interface is not working .

Note : all other entrys are ok and if i delete any other using web interface it works .

**Comment by TheNocturnalDev** [comment]
http://www.h2database.com/html/quickstart.html

**Comment by peterpt** [comment]
Thank you TheNocturnalDev for the tip .
does anyone here knows the username and password used by streama app to connect to the database ?

**Comment by peterpt** [comment]
Got it , it is in this file https://github.com/streamaserver/streama/blob/master/grails-app/conf/application.yml

it is "root" only for production
