### ISSUE TITLE
the sound is not heard in the movies

### ISSUE THREAD

**Issue by xhmartin** [streamaserver/streama#873]
the movies do come up well but they can't be heard, what could it be, help

**Comment by xhmartin** [comment]
I was reviewing streama and it only happens with MKV files with the other formats if they are heard well, any idea so that the MKV can be heard

**Comment by TheNocturnalDev** [comment]
MKV's arent recommended for this reason, html does not allow you to select an audio track inside a video as it doesnt have a way to browse the videos contents (or so).

Its recommended to use handbrake or something similar to convert all videos to H264 video encoding with the audio converted to 2 channel.

html doesnt support 5 channel audio

**Comment by Norwelian** [comment]
I have 5.1 AAC audio channels in some MKVs, and they play fine :/
At least on chrome and firefox!
But yeah, with the right codecs, and the more widely supported mp4 container on html5, all this kind of problems may be totally halted.

**Comment by drexlma** [comment]
https://en.wikipedia.org/wiki/HTML5_video -> Codes

**Comment by f1reflyyyylmao** [comment]
@xhmartin Check out the documentation for a simple line to copy-paste. It uses ffmpeg and when your video already works transcoding the audio to aac is very fast:
https://streamaserver.org/about/video-codecs/
Audio-only conversion is covered in the second ffmpeg line
