### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by peterpt** [streamaserver/streama#875]
Looks like the denveloper abandoned the project , however i have a question to everyone .

Does anyone knows how to get the tcp http/s requests log for streama ?
The objective is to use fail2ban to prevent hacking and brute force to the app .

**Comment by TheNocturnalDev** [comment]
dularion didnt abandon it, she has a real job and if recommend you use a reverse proxy like nginx if you want web request logs

**Comment by dularion** [comment]
Yep, I agree with @TheNocturnalDev. You should use apache/nginx as a reverse proxy, and then you'll have your access log there

**Comment by drexlma** [comment]
use NGINX-Revers-Proxy + GEOBlock + WAF

**Comment by peterpt** [comment]
Yup i know how it is done , however the problem is that i already have port 80 occupied and i dont want to open another port .
but i also could test a different perspective , witch is put streama running only on local host .

Example :  Streama server running on port 127.0.0.1:8080

and then i configure nginx to port ex: 192.168.1.70:8080 on lan ip that would serve as reverse proxy to 127.0.0.1:8080 .
This way i don't need to open additional tcp ports on external ip address .
Anyway , thanks for the help .
