### ISSUE TITLE
Unable to Login with demoUser

### ISSUE THREAD

**Issue by naeemghumman** [streamaserver/streama#877]
Hello @dularion 

[https://demo.streamaserver.org/](url)
Username: demoUser
Password: demoUser

Login failed with below error:
**Sorry, we were not able to find a user with that username and password.**

Please look into the issue. Thanks

**Comment by dularion** [comment]
it seems like someone broke the user :D usually something like this is fixed during the nightly rebuild that is run, but i re-ran it now. everything works again.

**Comment by acesuares** [comment]
not working today

**Comment by dularion** [comment]
Login works for me now

**Comment by dularion** [comment]
I guess some users play around with the user and change the password or some bullshit. I can maybe have the reset be triggered more than once every 24 hours.
