### ISSUE TITLE
Subtitles Size very small in recent browsers versions

### ISSUE THREAD

**Issue by peterpt** [streamaserver/streama#878]
Well , this is a bug , that i have no doubt .
Setting The Subtitles in maximum size in firefox 52 i get the subtitles with acceptable
size to be read .
But when i change to firefox 60 , the subtitles also setting up in their max size in streama stays very small , hardly to read .
Is there a way to fix this .
Actually i think that the maximum size should be much bigger than firefox 52 actually shows .
Anyway , here are the print screens .

Firefox 52 , streama configured with subtitles in Max size
![firefox52](https://user-images.githubusercontent.com/7487321/65985708-41a53580-e47a-11e9-9fad-6a4f8e32c8cd.jpg)

Firefox 60  , streama configured with subtitles in Max size (Impossible to read).
![firefox60](https://user-images.githubusercontent.com/7487321/65985746-5386d880-e47a-11e9-9a0b-a292f45a22c3.jpg)

**Comment by MagicD3VIL** [comment]
Still a problem in the new version of Firefox. Works fine in Chrome

**Comment by peterpt** [comment]
yup , this is why i have 2 firefox versions installed , the 52 esr and the latest , when i want to watch some movie using streama i will use 52 version , and when i want to surf the web i will use the latest .
I dont like Chrome , however this is probably not a streama bug but a firefox incompatibility , but i am not sure .

**Comment by prwilliam** [comment]
Adding some larger sizes in favour of compatibility might be a good idea even if it is not a streama bug

**Comment by dularion** [comment]
hm thats very unfortunate... i think ill just add a custom font size input, so you guys can scale it however you like
