### ISSUE TITLE
Problen install windows

### ISSUE THREAD

**Issue by leoortega77** [streamaserver/streama#887]
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------

how to install on win 10 ?

**Comment by f1reflyyyylmao** [comment]
https://streamaserver.org/getting-started/installing/#windows

**Comment by leoortega77** [comment]
I already read that.
but I do not understand. I am not an expert PC user
There is no executable to install?

**Comment by f1reflyyyylmao** [comment]
No. What step do you have a problem with exactly?

**Comment by leoortega77** [comment]
This:
Run
Start Command Prompt or Powershell in the directory with the streama-X.Y.jar you downloaded.

java -jar streama-X.Y.jar
You should see the following output after a short time.

Grails application running at http://localhost:8080 in environment: production

**Comment by f1reflyyyylmao** [comment]
So whats your problem with that? You start a command promt in the directory and run the jar with the command provided.

**Comment by leoortega77** [comment]
when I run it this comes out:

PS C:\Users\leoor> java -jar streama-X.Y.jar
java : El término 'java' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable.
Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e
inténtelo de nuevo.
En línea: 1 Carácter: 1
+ java -jar streama-X.Y.jar
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (java:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by leoortega77** [comment]
![Sin títulño](https://user-images.githubusercontent.com/57604024/68576924-d6be2580-044d-11ea-8019-254ce7c9a84a.png)
![Sin título](https://user-images.githubusercontent.com/57604024/68576927-da51ac80-044d-11ea-9467-c18a5b4f09ce.jpg)

**Comment by f1reflyyyylmao** [comment]
https://www.decodingdevops.com/how-to-install-java-in-windows-7-8-10/
You probably have to set up the environment variable first

**Comment by leoortega77** [comment]
ITS DONE...
![Sin título22](https://user-images.githubusercontent.com/57604024/68578419-b80d5e00-0450-11ea-9cbf-a6220324ee28.jpg)

but now this comes out

**Comment by f1reflyyyylmao** [comment]
You have to use the name of the actual jar file, not the generic version numbers X.Y ...

**Comment by leoortega77** [comment]
java -jar streama-1.7.3.jar ?

**Comment by f1reflyyyylmao** [comment]
yes

**Comment by leoortega77** [comment]
![Sin título3](https://user-images.githubusercontent.com/57604024/68579737-9e214a80-0453-11ea-86d9-c4ede0569a61.jpg)

**Comment by f1reflyyyylmao** [comment]
you have to execute the command in the directory you downloaded the jar file to

**Comment by leoortega77** [comment]
I have it in the downloads folder
How should the command be?

**Comment by f1reflyyyylmao** [comment]
You navigate to the downloads folder first
https://lmgtfy.com/?q=navigate+dirs+with+cmd&s=d&t=w

**Comment by leoortega77** [comment]
its done.
Now what's next?
http://192.168.1.1:8080 ?


![Sin título6](https://user-images.githubusercontent.com/57604024/68581376-0e7d9b00-0457-11ea-97ba-a4903f0b38d5.jpg)

**Comment by f1reflyyyylmao** [comment]
have you created an application.yml in the same directory as the jar file? If not, heres the documentation:
https://streamaserver.org/config/application.yml/

Just copy the sample file from https://github.com/streamaserver/streama/blob/master/docs/sample_application.yml and place it next to the jar.

**Comment by leoortega77** [comment]
I open a text file and modify it with those lines , 
Did I change the extension of txt to yml?

**Comment by f1reflyyyylmao** [comment]
i don't know if you did, but in case you didn't you should do so, yes.

**Comment by leoortega77** [comment]
It doesn't work for me, thank you too, I give up, it's very difficult to set up for someone who doesn't know about programming.

**Comment by f1reflyyyylmao** [comment]
why doesnt it work? did you change the file extension or not?

**Comment by leoortega77** [comment]
I created a file with the example lines, rename it "application.yml", and put it in the downloads folder where the streama.jar file is.
Then I go to the browser and try to enter from http: // localhost: 8080. but does not load the page

**Comment by f1reflyyyylmao** [comment]
have you started the program on the command line as before? you have to restart streama every time you change the configuration options in the application.yml for the changes to apply. to be able to use streama in your browser the program has to be running in your console window.

**Comment by leoortega77** [comment]
si lo hice, gracias!  
no lo gro hacer q ande.
seguramente algo estoy haciendo mal. te repito que no soy programador, solo un simple usuario de pc.
gracias de nuevo

**Comment by f1reflyyyylmao** [comment]
i cant help you if you dont tell me whats happening. also, since we use this more like a chat than an issue tracker, why dont you join me on https://hack.chat/?streama-help so we can chat directly?

**Comment by Grabisoft** [comment]
> i cant help you if you dont tell me whats happening. also, since we use this more like a chat than an issue tracker, why dont you join me on https://hack.chat/?streama-help so we can chat directly?

hi f1reflyyyylmao, i will need your assistance as well. im having the same problem as leo. can you help me out using teamviewer?
