### ISSUE TITLE
New Dashboard UI like netflix

### ISSUE THREAD

**Issue by dularion** [streamaserver/streama#888]
Since streama launched, the netflix UI has upgraded a bit, and now on the dashboard we have the traditional card-vie under "home" as well as Tv Shows, Movies, Recently Added & My List. This ties in with https://github.com/streamaserver/streama/issues/590. Basically, we should also add a multi-page dashboard like on netflix :)

![image](https://user-images.githubusercontent.com/936076/68745148-656da680-05f6-11ea-851b-987b56b41d8b.png)

![image](https://user-images.githubusercontent.com/936076/68745544-1f651280-05f7-11ea-8159-06cf44bf3a2b.png)

**Comment by juininhojr** [comment]
is beautiful <3, already have a forecast when will release this update ??

**Comment by dularion** [comment]
a first draft for this (new links & prettier header) is coming up in the next release
