### ISSUE TITLE
Unable to Login with demoUser

### ISSUE THREAD

**Issue by acesuares** [streamaserver/streama#929]
### Issue description
see https://github.com/streamaserver/streama/issues/877

**Comment by peterpt** [comment]
On readme file : 
credentials: username: demoUser | password: demoUser
Feel free to play around there as much as you like (everything is reset at night)

So , what you have to do is to test it tomorrow  .

**Comment by acesuares** [comment]
... okay, but #877 said that it was fixed on sept 25
sorry to misunderstand

**Comment by acesuares** [comment]
also, 'night' may differ from place to place :-)

**Comment by dularion** [comment]
Login works for me now

I guess some users play around with the user and change the password or some bullshit. I can maybe have the reset be triggered more than once every 24 hours.

**Comment by acesuares** [comment]
It works now. Maybe just prevent de demoUser from being edited. Looks very nice!
