### ISSUE TITLE
Cannot fastfoward remote video files

### ISSUE THREAD

**Issue by glinskicwb1988** [streamaserver/streama#934]
### Issue description

If you try to fastfoward a video (a remote one), you simply cant. If you use a local video, you can fastfoward normally.

Tryied using a MKV file and a Mp4 file. So maybe it's not a codec issue ?

### Steps to Reproduce

1. Add a movie and choose a link for the video file outside your home server (eg: someplace.com/video.mp4)
2. Play the video and try to fastfoward it.

### Expected Behaviour
You should be able to advance the video to the time you want.

### Actual Behaviour
The video bar wont go foward and the video don't fastfoward to the position you want.

### Environment Information

- **Operating System**: CentOS 7
- **Streama version**: 1.8

**Comment by dularion** [comment]
so that other server needs to handle certain html5 headers, such as the range header and the progressive download.. check out this guide http://ronallo.com/blog/html5-video-everything-i-needed-to-know/

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.
