### ISSUE TITLE
Video streaming is slower in PC than Android

### ISSUE THREAD

**Issue by hurondefuego** [streamaserver/streama#938]
### Issue description
When I'm watching a movie or serie in my laptop (client), the video doesn't load fast, but if watch the same video on my phone, the video loads with no problem. All the video files are stored in my server, and the connection is local, the server only can be accessed in my LAN.

My client computer is a Macbook Air 2015.
My phone is a Samsung Galaxy A7 2017.

So I wanna know what can I do to reproduce them as good as the android device.

### Environment Information
By the way, I'm using a recycled computer for the server with these specifications:

- **Computer**: Toshiba Satellite L455 (Notebook)
- **Operating System**: Xubuntu 18.04 x64
- **Processor**: Intel Celeron CPU 900 (2.20 GHz)
- **RAM**: 2GB
- **HDD**: 500GB
- **Streama version**: 1.8.0

Is my server's hardware part of the problem? I'm thinking on changing the operating system and I other lighter like Bunsen Labs.

**Comment by Saentist** [comment]
Change browser, add more ram.

**Comment by hurondefuego** [comment]
Thank you @Saentist 

I will close this issue. I solved it and the solution was so easy, but please don't erase this post, because it can help others with my problem.

The problem was the WLAN chipset. Because I'm using a recycled laptop as server, the network card is not working properly, so it receives a poor WiFi signal. I had to place my repeater next to my server.
I don't use Ethernet because I don't have physical access to the main router/modem. 

Now the video streaming is as fast as Netflix.

:)
