### ISSUE TITLE
Email users in order to register through Gmail SMPT

### ISSUE THREAD

**Issue by Erudes** [streamaserver/streama#940]
Hello, 

I want to send invites to my users so they can complete registration process and I have my domain linked to GSuite Google Cloud. So where do I configure this on my server?
https://github.com/streamaserver/streama/wiki/Email-configuration
According to this there is an .yml file, but where do I find it?

Thanks!

**Comment by LukeSteward** [comment]
Hi,

You need to make the application.yml file yourself if you would like a template please use https://github.com/streamaserver/streama/blob/master/docs/sample_application.yml
