### ISSUE TITLE
Cannot get property 'id' on null object

### ISSUE THREAD

**Issue by xilmen** [streamaserver/streama#946]
Hello, 

i can't add contant automatically. Can you  help me ?

### Issue description
Streama error :
`not all files were added unfortunately. This is due to TheMovieDB API LIMIT constraints. Just try again in a couple of seconds :)`

Java Logs

`WARN grails.app.services.streama.TheMovieDbService - could not load fullMeta for Movie this time, https://api.themoviedb.org/3/movie/null?api_key=MYAPIKEY&language=fr-FR
ERROR grails.app.services.streama.TheMovieDbService - Error occured while trying to retrieve data from TheMovieDB: Cannot get property 'id' on null object
java.lang.NullPointerException: Cannot get property 'id' on null object`

i try with other languages ... it's same. 

### Steps to Reproduce
Same as your doc
https://user-images.githubusercontent.com/936076/29990709-8f34e8f8-8f7d-11e7-9d9b-955236bf2251.gif

- **Operating System**: FreeNAS (latest) jail
- **Streama version**: 1.7.3 or 1.6.7

**Comment by xilmen** [comment]
i make one more test, he works for tvshow, but not for movies

**Comment by ryanherbison** [comment]
It also occurs on 1.7.2 and 1.8 Beta - Issue occurs for me when adding movies. I have not noticed the issue when adding shows.

**Comment by ryanherbison** [comment]
Errors on: whats.eating.gilbert.grape.1993.1080p.BluRay.YiFy.test.mp4
Also Errors: Whats.Eating.Gilbert.Grape.1993.1080p.BluRay.x264.YIFY.processed.mp4
Does not error on and successfully imports: whats.eating.gilbert.grape.1993.mp4
I guess files need renaming.

**Comment by xilmen** [comment]
I try with other file name like: 
a.name.movie.mkv

I test with streama 1.7.2 and 1.8 with java 1.8.0_231-b11 and 1.8.0_232-b09 and, i have a same error :( 

mkv file create probleme ? 
What is your java version ?

**Comment by xilmen** [comment]
Fix with streamaserver 1.8.1
