### ISSUE TITLE
add options for de/activating the general sections 'Tv Shows', 'Movies' and 'My List'

### ISSUE THREAD

**Issue by paulkitt** [streamaserver/streama#947]
### Issue description
A lot of people doing classes for their living are forced to stay home and shut down their businesses.
Stremea would be a great option for making private class videos available without requesting people to join youtube or vimeo.

Would it be possible to add options for renaming and de/activating the general sections 'Tv Shows', 'Movies' and 'My List'?

**Comment by dularion** [comment]
yea good point :)
