### ISSUE TITLE
Expired certificate demo version

### ISSUE THREAD

**Issue by Thovi98** [streamaserver/streama#948]
### Issue description
On demo.streamaserver.org, there is an alert for security problem. It sais that certificate is expired from 28/03/2020 (today). 

### Steps to Reproduce
Go to https://demo.streamaserver.org/ and see. 

1. TODO : renew certificate

**Comment by dularion** [comment]
yep, this is onhoing. thanks :)

**Comment by tet3** [comment]
Site is now down altogether - points to namecheap parking servers with A records, but they give a 502 Bad Gateway on http and refuse connection on https. Removing demo link from https://github.com/awesome-selfhosted/awesome-selfhosted/ listing.

**Comment by Thovi98** [comment]
I’ve just seen the new link for the demo version, it works fine, thanks !

Huge thank for all your great work @dularion :D

**Comment by dularion** [comment]
Thanks for noticing :)
