### ISSUE TITLE
UNISNTALL Streama Server completely from Ubuntu Server 18.0.4

### ISSUE THREAD

**Issue by roosho** [streamaserver/streama#952]
### UNISNTALL Streama Server completely from Ubuntu Server 18.0.4

I don't know how to uninstall everything regarding to Streama Server from my Ubuntu server. Can any one help me with the steps?

### Environment Information

- **Operating System**: Ubuntu Server 18.0.4 LTS
- **Streama version**: 1.8.0

**Comment by Thomas-Clauzel** [comment]
i think you just need to stop the service, remove the data, remove java with apt remove

**Comment by roosho** [comment]
> 
> 
> i think you just need to stop the service, remove the data, remove java with apt remove

Sorry for being late.

How do I remove data!
Where shall I find those?

**Comment by dularion** [comment]
Data is only stored in the directories that you configured during setup, ie the upload directory

**Comment by dularion** [comment]
And ofc the mysql database

**Comment by roosho** [comment]
> 
> 
> And ofc the mysql database

I think this is what I was missing.

**Comment by roosho** [comment]
> 
> 
> And ofc the mysql database

I cannot find the database. it seems **mysql-server** do not have any database except the defaults. 
I exactly followed the instructions for Ubuntu from here:
https://streamaserver.org/getting-started/installing/
Can you help me out please.
Thanks

**Comment by dularion** [comment]
In that case you are using the built-in h2 database, which looks like this: 

![image](https://user-images.githubusercontent.com/936076/78599989-637cdc00-7852-11ea-8cde-e4a8992c38bf.png)

you should delete those two files
