### ISSUE TITLE
The database is read only

### ISSUE THREAD

**Issue by manhast** [streamaserver/streama#964]
hi everyone, I can't start streama 1.8.2 as an ubuntu server service, on 1.8.0 it worked.
if I start from command* it works but not from service, it gives me this error:

`Apr 13 18:29:03 streama streama-1.8.2.jar[1745]: INFO streama.Application - Starting Application on streama with PID 1771 (/data/streama/streama-1.8.2.jar started by manhast in /data/streama)
Apr 13 18:29:03 streama streama-1.8.2.jar[1745]: DEBUG streama.Application - Running with Spring Boot v1.4.4.RELEASE, Spring v4.3.6.RELEASE
Apr 13 18:29:03 streama streama-1.8.2.jar[1745]: INFO streama.Application - The following profiles are active: production
Apr 13 18:29:47 streama streama-1.8.2.jar[1745]: Configuring Spring Security Core ...
Apr 13 18:29:48 streama streama-1.8.2.jar[1745]: ... finished configuring Spring Security Core
Apr 13 18:29:49 streama streama-1.8.2.jar[1745]: Configuring Spring Security LDAP ...
Apr 13 18:29:49 streama streama-1.8.2.jar[1745]: ... finished configuring Spring Security LDAP
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]: ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - The database is read only; SQL statement:
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]: insert into genre (version, api_id, name) values (?, ?, ?) [90097-193]
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]: ERROR org.springframework.boot.SpringApplication - Application startup failed
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]: org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not execute statement; uncategorized SQLException for SQL [n/a]; SQL state [90097]; error code [90097]; The database is read only; SQL statement:
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]: insert into genre (version, api_id, name) values (?, ?, ?) [90097-193]; nested exception is org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]: insert into genre (version, api_id, name) values (?, ?, ?) [90097-193]
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]:         at org.grails.orm.hibernate.GrailsHibernateTemplate.convertJdbcAccessException(GrailsHibernateTemplate.java:711)
Apr 13 18:31:56 streama streama-1.8.2.jar[1745]:         at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:699)
.
.
.
a long list goes on`

### Environment Information

- **Operating System**: Ubuntu server 18.04.4 LTS
- **Streama version**: 1.8.2

I applied streama as a service from like this guide: https://dzone.com/articles/run-your-java-application-as-a-service-on-ubuntu

*if I start streama with `sudo ./streama-1.8.2.jar` , it works

streama is allocated in /data/streama and i have: 
media  serviziostreama.sh(this is bash for service)  streama-1.8.2.jar  streama.mv.db  streama.trace.db

serviziostreama.sh:
```
#!/bin/sh
sudo chmod o+x /usr/bin/java -jar streama-1.8.2.jar
```

I don't know if you need anything else? thanks for help

**Comment by dularion** [comment]
maybe this helps https://stackoverflow.com/questions/46842586/tomcat-error-embedded-h2-db-read-only

Seems like the user executing your service  (if you followed the guide, then `User=ubuntu`) doesnt have write permission on streama.mv.db or  streama.trace.db. Weird tho, why would the 1.8.2 update cause this? 🤔
I'll look at it more, but a screenshot or similar of your permission structure within /data/streama would be helpful

**Comment by manhast** [comment]
structure: /data/streama/files and folder media

DATA: drwxr-xr-x   3 root root       4096 Apr 11 15:49 data
STREAMA: drwxr-xr-x 3 root root 4096 Apr 13 19:03 streama
drwxr-xr-x 3 root root     4096 Apr 11 16:27 media (folder)
-rwxr-xr-x 1 root root       62 Apr 12 23:27 serviziostreama.sh
-rwxrwxrwx 1 root root 98439076 Apr 12 15:40 streama-1.8.2.jar
-rw-r--r-- 1 root root   172032 Apr 12 23:15 streama.mv.db
-rw-r--r-- 1 root root    36722 Apr 12 23:11 streama.trace.db


now I try to check with the link you gave me.

**Comment by dularion** [comment]
all right, well the string `-rw-r--r--` says, that only the owner (root) may write on this file. So if your server is configured to use ANY other use than root, it wont be able to write to the database.

**Comment by manhast** [comment]
it works! I set the permissions.
it was a simple problem and I was unable to identify what an idiot I am. 
Thank you so muchhhhhh

**Comment by dularion** [comment]
nice :)
