### ISSUE TITLE
admin option to hide the search functionality

### ISSUE THREAD

**Issue by munferig** [streamaserver/streama#971]
I have an idea that coud be interesting.

- An admin option to hide the search functionality, or might be just search on the section selected
(A few days ago I started using streama to share some videos with my students. I've created users and profiles grouped by academic level. Hiding some sections and adding to the watchlist the students can see only their level videos. Unfortunately the students started to use the search functionality to find and access all videos )

In any case great app

**Comment by dularion** [comment]
Interesting! Yeah sure, I can make it optional

**Comment by munferig** [comment]
wow!! great, thanks
