### ISSUE TITLE
prod/AE/image-fix branch bugs

### ISSUE THREAD

**Issue by AgileGhost** [streamaserver/streama#977]
### Issue description
prod/AE/image-fix branch has two problems that I've noticed so far. 

Number 1, is that the dashboard highlights are replaced with massive images that aren't scaled down so it takes up a large portion of the screen as you can see in the image below. (This image is zoomed out). 

Number 2, is that the posters that are replaced have duplicates underneath the other. It doesn't show on up anywhere else except the popout on the dash and sometimes the dash highlights. (seen in the image below)

### Environment Information

- OS: Ubuntu 18.04.3
- Version: streama-1.9.0-prod-AE-image-fix

![unknown](https://user-images.githubusercontent.com/61676371/81048246-527dc400-8eff-11ea-8470-82d849aec7be.png)

![unknown1](https://user-images.githubusercontent.com/61676371/81048255-5578b480-8eff-11ea-9d17-283431cc2120.png)

**Comment by dularion** [comment]
Thanks for the ticket ! working on it now

**Comment by dularion** [comment]
i fixed the double image in the popup, but i couldnt reproduce the other issue... for me the highlights looks just fine. any chance you can point me in the right direction?
