### ISSUE TITLE
TV Show not added after filling out Add Manually form

### ISSUE THREAD

**Issue by mauriciolazo** [streamaserver/streama#978]
### Issue description
There is no response or action when clicking on the "Save Show" button after adding manually the information at the "TV Shows" --> "Add Manually" form. All information is in the correct format and it has an IMDB ID. 

### Steps to Reproduce

1. Log In
2. Select Profile
3. Select Manage Content
4. Select TV Shows
5. Create New Show
6. Add Manually
7. Fill out the form
8. Click on Save Show

### Expected Behaviour
Show is created and is listed under the TV Show section at Manage Content.

### Actual Behaviour
After clicking on Create Show, there is no response. If I click on Cancel or outside the form, there is response and regular behavior in everything else.

### Environment Information

- **Server Operating System**: Ubuntu 18.04.4
- **Streama version**: 1.8.3
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: No customization performed to Streama. Streama is hosted on a home network server and it is accessed through an NGINX reverse proxy. Setup is:    Internet <--https--> NGINX(reverse proxy) <--http--> Ubuntu Server (Streama started as a service with Systemd and Open JDK8).
- **Container Version (If Applicable):** Not Applicable.

**Comment by mauriciolazo** [comment]
Update: Chrome Developer Tools shows the following error on clicking the "Save Show" button: 

```
**Error #1:** 
POST https://MYSELFHOSTEDSERVER/tvShow/save.json 406
(anonymous) @ vendor.unminified.js:26215
y @ vendor.unminified.js:25972
(anonymous) @ vendor.unminified.js:25635
(anonymous) @ vendor.unminified.js:30641
$digest @ vendor.unminified.js:31706
$apply @ vendor.unminified.js:32131
(anonymous) @ vendor.unminified.js:41638
dispatch @ vendor.unminified.js:7597
m.handle @ vendor.unminified.js:7304

**Error#2:**
vendor.unminified.js:28266 Possibly unhandled rejection: {"data":{"timestamp":1588867760877,"status":406,"error":"Not Acceptable","message":"No message available","path":"/tvShow/save.json"},"status":406,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"tvShow/save.json","data":{"manualInput":true,"name":"Ron Finley Teaches Gardening","first_air_date":"2020/04/14","dateCreated":"2020/04/30","imdb_id":"tt0383126","overview":"Ron Finley Teaches Gardening"},"headers":{"Accept":"application/json, text/plain, */*","X-Requested-With":"XMLHttpRequest","Content-Type":"application/json;charset=utf-8","profileId":3},"params":{}},"statusText":"","xhrStatus":"complete"}
(anonymous) @ vendor.unminified.js:28168
(anonymous) @ vendor.unminified.js:24418
l @ vendor.unminified.js:30595
$digest @ vendor.unminified.js:31706
$apply @ vendor.unminified.js:32131
h @ vendor.unminified.js:25997
u @ vendor.unminified.js:26309
w.onload @ vendor.unminified.js:26299
![streama-troubleshooting](https://user-images.githubusercontent.com/16341154/81319021-4eab8800-904c-11ea-8cff-a8fa4b85bcdd.PNG)

load (async)
(anonymous) @ vendor.unminified.js:26299
y @ vendor.unminified.js:25972
(anonymous) @ vendor.unminified.js:25635
(anonymous) @ vendor.unminified.js:30641
$digest @ vendor.unminified.js:31706
$apply @ vendor.unminified.js:32131
(anonymous) @ vendor.unminified.js:41638
dispatch @ vendor.unminified.js:7597
m.handle @ vendor.unminified.js:7304

```

Additionally, if I create the TV Show and add all the information at themoviedb.org website, then Streama imports the information perfectly fine.

**Comment by dularion** [comment]
i cant reproduce this, checked it on the demo-version, too https://streama.demo-version.net/#!/admin/show/11

**Comment by LukeSteward** [comment]
Due to inactivity surrounding this topic I am closing it. If this is not solved please reopen the issue.
