### ISSUE TITLE
Display server hostname (feature request)

### ISSUE THREAD

**Issue by rascal999** [streamaserver/streama#980]
### Issue description

Can hostname of server be output on page footer alongside Streama version? I run multiple instances of streama and this would be a helpful addition.

**Comment by coamtaker618** [comment]
Would hostname be more desirable than adding a text name box (maybe character limited) configurable by the admin?

**Comment by dularion** [comment]
I like that idea, a custom Footer text, maybe even a wysiwyg so you can input html. ... :)

**Comment by coamtaker618** [comment]
As much as I want to say that's overkill...it would be cool to be able to adjust colors & font size & such!  All I ask is that you keep it easy for inputting "simple plain text" :)

@rascal999  what's the benefit of running multiple instances of Streama?  Unless you're running it for HA/failover (is this even a thing?)--which I totally get!

**Comment by rascal999** [comment]
@coamtaker618 I'm running Streama in a k8s cluster with replicas. Streama doesn't work well in such a setup, so I've had to set session affinity based on client IP (so clients will always hit the same pod).

It's mainly a training exercise for me, but I never know which pod is serving the web page I'm looking at.

@dularion would it be possible to reference Java variables in this footer?

**Comment by coamtaker618** [comment]
@rascal999 Sad to hear that that Streama is unhappy in kubernetes :(    But I totally understand the motivation!!
